; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	C:\DUII\Simulation\GUI\Widget\BUTTON_SkinFlex.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
__apProps DD	FLAT:__PropsPressed
	DD	FLAT:__PropsFocussed
	DD	FLAT:__PropsEnabled
	DD	FLAT:__PropsDisabled
CONST	ENDS
_DATA	SEGMENT
__PropsPressed DD 08b622cH
	DD	0bab09eH
	DD	0efd198H
	DD	0fcf4e5H
	DD	0f6e5c4H
	DD	0efd198H
	DD	0dbb368H
	DD	04H
__PropsFocussed DD 0b17f3cH
	DD	0fbd846H
	DD	0dfdfdfH
	DD	0f3f3f3H
	DD	0ecececH
	DD	0dfdfdfH
	DD	0d0d0d0H
	DD	04H
__PropsEnabled DD 0707070H
	DD	0fcfcfcH
	DD	0dfdfdfH
	DD	0f3f3f3H
	DD	0ecececH
	DD	0dfdfdfH
	DD	0d0d0d0H
	DD	04H
__PropsDisabled DD 0b5b2adH
	DD	0fcfcfcH
	DD	0f4f4f4H
	DD	0f4f4f4H
	DD	0f4f4f4H
	DD	0f4f4f4H
	DD	0f4f4f4H
	DD	04H
_DATA	ENDS
PUBLIC	_BUTTON_DrawSkinFlex
EXTRN	_WM_SetHasTrans:PROC
EXTRN	_GUI_DispStringInRect:PROC
EXTRN	_GUI_ALLOC_LockH:PROC
EXTRN	_GUI_SetTextMode:PROC
EXTRN	_GUI_GetClientRect:PROC
EXTRN	_GUI_SetFont:PROC
EXTRN	_GUI_DRAW__Draw:PROC
EXTRN	_GUI_ALLOC_UnlockH:PROC
EXTRN	_BUTTON_LockH:PROC
EXTRN	_GUI_DrawGradientV:PROC
EXTRN	_GUI_DrawRect:PROC
EXTRN	_GUI_FillRect:PROC
EXTRN	_GUI_DrawVLine:PROC
EXTRN	_GUI_DrawHLine:PROC
EXTRN	_GUI_SetColor:PROC
EXTRN	_GUI__DrawTwinArc4:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	@_RTC_CheckStackVars@8:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	__RTC_InitBase:PROC
;	COMDAT rtc$TMZ
; File c:\duii\simulation\gui\widget\button_skinflex.c
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
; Function compile flags: /Odtp /RTCsu /ZI
rtc$IMZ	ENDS
;	COMDAT _BUTTON_DrawSkinFlex
_TEXT	SEGMENT
tv290 = -344						; size = 4
tv68 = -344						; size = 4
_s$ = -144						; size = 4
_hText$ = -132						; size = 4
_pProps$ = -120						; size = 4
_Rect$ = -108						; size = 8
_hDrawObj$ = -92					; size = 4
_Color$ = -80						; size = 4
_Radius$ = -68						; size = 4
_TextAlign$ = -56					; size = 4
_ColorIndex$ = -44					; size = 4
_BitmapIndex$ = -32					; size = 4
_y$ = -20						; size = 4
_pObj$ = -8						; size = 4
_pDrawItemInfo$ = 8					; size = 4
_BUTTON_DrawSkinFlex PROC				; COMDAT
; Line 102
	push	ebp
	mov	ebp, esp
	sub	esp, 344				; 00000158H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-344]
	mov	ecx, 86					; 00000056H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 115
	mov	eax, DWORD PTR _pDrawItemInfo$[ebp]
	mov	ecx, DWORD PTR [eax+8]
	mov	edx, DWORD PTR __apProps[ecx*4]
	mov	DWORD PTR _pProps$[ebp], edx
; Line 119
	mov	eax, DWORD PTR _pDrawItemInfo$[ebp]
	mov	ecx, DWORD PTR [eax+4]
	mov	DWORD PTR tv68[ebp], ecx
	cmp	DWORD PTR tv68[ebp], 16			; 00000010H
	ja	$LN17@BUTTON_Dra
	mov	edx, DWORD PTR tv68[ebp]
	movzx	eax, BYTE PTR $LN23@BUTTON_Dra[edx]
	jmp	DWORD PTR $LN27@BUTTON_Dra[eax*4]
$LN16@BUTTON_Dra:
; Line 121
	mov	eax, DWORD PTR _pProps$[ebp]
	cmp	DWORD PTR [eax+28], 0
	je	$LN15@BUTTON_Dra
; Line 125
	mov	eax, DWORD PTR _pProps$[ebp]
	mov	ecx, DWORD PTR [eax+8]
	push	ecx
	mov	edx, DWORD PTR _pProps$[ebp]
	mov	eax, DWORD PTR [edx+4]
	push	eax
	mov	ecx, DWORD PTR _pProps$[ebp]
	mov	edx, DWORD PTR [ecx]
	push	edx
	mov	eax, DWORD PTR _pProps$[ebp]
	mov	ecx, DWORD PTR [eax+28]
	push	ecx
	mov	edx, DWORD PTR _pDrawItemInfo$[ebp]
	mov	eax, DWORD PTR [edx+24]
	push	eax
	mov	ecx, DWORD PTR _pDrawItemInfo$[ebp]
	mov	edx, DWORD PTR [ecx+20]
	push	edx
	mov	eax, DWORD PTR _pDrawItemInfo$[ebp]
	mov	ecx, DWORD PTR [eax+16]
	push	ecx
	mov	edx, DWORD PTR _pDrawItemInfo$[ebp]
	mov	eax, DWORD PTR [edx+12]
	push	eax
	call	_GUI__DrawTwinArc4
	add	esp, 32					; 00000020H
; Line 129
	mov	DWORD PTR _y$[ebp], 0
	jmp	SHORT $LN14@BUTTON_Dra
$LN13@BUTTON_Dra:
	mov	eax, DWORD PTR _y$[ebp]
	add	eax, 1
	mov	DWORD PTR _y$[ebp], eax
$LN14@BUTTON_Dra:
	cmp	DWORD PTR _y$[ebp], 2
	jge	$LN12@BUTTON_Dra
; Line 130
	mov	eax, DWORD PTR _y$[ebp]
	mov	ecx, DWORD PTR _pProps$[ebp]
	mov	edx, DWORD PTR [ecx+eax*4]
	mov	DWORD PTR _Color$[ebp], edx
; Line 131
	mov	eax, DWORD PTR _Color$[ebp]
	push	eax
	call	_GUI_SetColor
	add	esp, 4
; Line 132
	mov	eax, DWORD PTR _pDrawItemInfo$[ebp]
	mov	ecx, DWORD PTR _pProps$[ebp]
	mov	edx, DWORD PTR [eax+20]
	sub	edx, DWORD PTR [ecx+28]
	push	edx
	mov	eax, DWORD PTR _pDrawItemInfo$[ebp]
	mov	ecx, DWORD PTR [eax+12]
	mov	edx, DWORD PTR _pProps$[ebp]
	add	ecx, DWORD PTR [edx+28]
	push	ecx
	mov	eax, DWORD PTR _pDrawItemInfo$[ebp]
	mov	ecx, DWORD PTR [eax+16]
	add	ecx, DWORD PTR _y$[ebp]
	push	ecx
	call	_GUI_DrawHLine
	add	esp, 12					; 0000000cH
; Line 133
	mov	eax, DWORD PTR _pDrawItemInfo$[ebp]
	mov	ecx, DWORD PTR _pProps$[ebp]
	mov	edx, DWORD PTR [eax+20]
	sub	edx, DWORD PTR [ecx+28]
	push	edx
	mov	eax, DWORD PTR _pDrawItemInfo$[ebp]
	mov	ecx, DWORD PTR [eax+12]
	mov	edx, DWORD PTR _pProps$[ebp]
	add	ecx, DWORD PTR [edx+28]
	push	ecx
	mov	eax, DWORD PTR _pDrawItemInfo$[ebp]
	mov	ecx, DWORD PTR [eax+24]
	sub	ecx, DWORD PTR _y$[ebp]
	push	ecx
	call	_GUI_DrawHLine
	add	esp, 12					; 0000000cH
; Line 134
	mov	eax, DWORD PTR _pDrawItemInfo$[ebp]
	mov	ecx, DWORD PTR _pProps$[ebp]
	mov	edx, DWORD PTR [eax+24]
	sub	edx, DWORD PTR [ecx+28]
	push	edx
	mov	eax, DWORD PTR _pDrawItemInfo$[ebp]
	mov	ecx, DWORD PTR [eax+16]
	mov	edx, DWORD PTR _pProps$[ebp]
	add	ecx, DWORD PTR [edx+28]
	push	ecx
	mov	eax, DWORD PTR _pDrawItemInfo$[ebp]
	mov	ecx, DWORD PTR [eax+12]
	add	ecx, DWORD PTR _y$[ebp]
	push	ecx
	call	_GUI_DrawVLine
	add	esp, 12					; 0000000cH
; Line 135
	mov	eax, DWORD PTR _pDrawItemInfo$[ebp]
	mov	ecx, DWORD PTR _pProps$[ebp]
	mov	edx, DWORD PTR [eax+24]
	sub	edx, DWORD PTR [ecx+28]
	push	edx
	mov	eax, DWORD PTR _pDrawItemInfo$[ebp]
	mov	ecx, DWORD PTR [eax+16]
	mov	edx, DWORD PTR _pProps$[ebp]
	add	ecx, DWORD PTR [edx+28]
	push	ecx
	mov	eax, DWORD PTR _pDrawItemInfo$[ebp]
	mov	ecx, DWORD PTR [eax+20]
	sub	ecx, DWORD PTR _y$[ebp]
	push	ecx
	call	_GUI_DrawVLine
	add	esp, 12					; 0000000cH
; Line 136
	jmp	$LN13@BUTTON_Dra
$LN12@BUTTON_Dra:
; Line 137
	mov	eax, DWORD PTR _pProps$[ebp]
	mov	ecx, DWORD PTR [eax+8]
	push	ecx
	call	_GUI_SetColor
	add	esp, 4
; Line 138
	mov	eax, DWORD PTR _pDrawItemInfo$[ebp]
	mov	ecx, DWORD PTR _pProps$[ebp]
	mov	edx, DWORD PTR [eax+24]
	sub	edx, DWORD PTR [ecx+28]
	push	edx
	mov	eax, DWORD PTR _pDrawItemInfo$[ebp]
	mov	ecx, DWORD PTR [eax+12]
	mov	edx, DWORD PTR _pProps$[ebp]
	mov	eax, DWORD PTR [edx+28]
	lea	ecx, DWORD PTR [ecx+eax-1]
	push	ecx
	mov	edx, DWORD PTR _pDrawItemInfo$[ebp]
	mov	eax, DWORD PTR [edx+16]
	mov	ecx, DWORD PTR _pProps$[ebp]
	add	eax, DWORD PTR [ecx+28]
	push	eax
	mov	edx, DWORD PTR _pDrawItemInfo$[ebp]
	mov	eax, DWORD PTR [edx+12]
	add	eax, 2
	push	eax
	call	_GUI_FillRect
	add	esp, 16					; 00000010H
; Line 139
	mov	eax, DWORD PTR _pDrawItemInfo$[ebp]
	mov	ecx, DWORD PTR _pProps$[ebp]
	mov	edx, DWORD PTR [eax+24]
	sub	edx, DWORD PTR [ecx+28]
	push	edx
	mov	eax, DWORD PTR _pDrawItemInfo$[ebp]
	mov	ecx, DWORD PTR [eax+20]
	sub	ecx, 2
	push	ecx
	mov	edx, DWORD PTR _pDrawItemInfo$[ebp]
	mov	eax, DWORD PTR [edx+16]
	mov	ecx, DWORD PTR _pProps$[ebp]
	add	eax, DWORD PTR [ecx+28]
	push	eax
	mov	edx, DWORD PTR _pDrawItemInfo$[ebp]
	mov	eax, DWORD PTR _pProps$[ebp]
	mov	ecx, DWORD PTR [edx+20]
	sub	ecx, DWORD PTR [eax+28]
	add	ecx, 1
	push	ecx
	call	_GUI_FillRect
	add	esp, 16					; 00000010H
; Line 140
	mov	eax, DWORD PTR _pProps$[ebp]
	mov	ecx, DWORD PTR [eax+28]
	mov	DWORD PTR _Radius$[ebp], ecx
; Line 141
	jmp	SHORT $LN11@BUTTON_Dra
$LN15@BUTTON_Dra:
; Line 145
	mov	DWORD PTR _y$[ebp], 0
	jmp	SHORT $LN10@BUTTON_Dra
$LN9@BUTTON_Dra:
	mov	eax, DWORD PTR _y$[ebp]
	add	eax, 1
	mov	DWORD PTR _y$[ebp], eax
$LN10@BUTTON_Dra:
	cmp	DWORD PTR _y$[ebp], 2
	jge	SHORT $LN8@BUTTON_Dra
; Line 146
	mov	eax, DWORD PTR _y$[ebp]
	mov	ecx, DWORD PTR _pProps$[ebp]
	mov	edx, DWORD PTR [ecx+eax*4]
	mov	DWORD PTR _Color$[ebp], edx
; Line 147
	mov	eax, DWORD PTR _Color$[ebp]
	push	eax
	call	_GUI_SetColor
	add	esp, 4
; Line 148
	mov	eax, DWORD PTR _pDrawItemInfo$[ebp]
	mov	ecx, DWORD PTR [eax+24]
	sub	ecx, DWORD PTR _y$[ebp]
	push	ecx
	mov	edx, DWORD PTR _pDrawItemInfo$[ebp]
	mov	eax, DWORD PTR [edx+20]
	sub	eax, DWORD PTR _y$[ebp]
	push	eax
	mov	ecx, DWORD PTR _pDrawItemInfo$[ebp]
	mov	edx, DWORD PTR [ecx+16]
	add	edx, DWORD PTR _y$[ebp]
	push	edx
	mov	eax, DWORD PTR _pDrawItemInfo$[ebp]
	mov	ecx, DWORD PTR [eax+12]
	add	ecx, DWORD PTR _y$[ebp]
	push	ecx
	call	_GUI_DrawRect
	add	esp, 16					; 00000010H
; Line 149
	jmp	SHORT $LN9@BUTTON_Dra
$LN8@BUTTON_Dra:
; Line 150
	mov	DWORD PTR _Radius$[ebp], 2
$LN11@BUTTON_Dra:
; Line 159
	mov	eax, DWORD PTR _pProps$[ebp]
	mov	ecx, DWORD PTR [eax+16]
	push	ecx
	mov	edx, DWORD PTR _pProps$[ebp]
	mov	eax, DWORD PTR [edx+12]
	push	eax
	mov	ecx, DWORD PTR _pDrawItemInfo$[ebp]
	mov	edx, DWORD PTR [ecx+16]
	mov	eax, DWORD PTR _pDrawItemInfo$[ebp]
	add	edx, DWORD PTR [eax+24]
	sar	edx, 1
	push	edx
	mov	ecx, DWORD PTR _pDrawItemInfo$[ebp]
	mov	edx, DWORD PTR [ecx+20]
	sub	edx, DWORD PTR _Radius$[ebp]
	push	edx
	mov	eax, DWORD PTR _pDrawItemInfo$[ebp]
	mov	ecx, DWORD PTR [eax+16]
	add	ecx, 2
	push	ecx
	mov	edx, DWORD PTR _pDrawItemInfo$[ebp]
	mov	eax, DWORD PTR [edx+12]
	add	eax, DWORD PTR _Radius$[ebp]
	push	eax
	call	_GUI_DrawGradientV
	add	esp, 24					; 00000018H
; Line 164
	mov	eax, DWORD PTR _pProps$[ebp]
	mov	ecx, DWORD PTR [eax+24]
	push	ecx
	mov	edx, DWORD PTR _pProps$[ebp]
	mov	eax, DWORD PTR [edx+20]
	push	eax
	mov	ecx, DWORD PTR _pDrawItemInfo$[ebp]
	mov	edx, DWORD PTR [ecx+24]
	sub	edx, 2
	push	edx
	mov	eax, DWORD PTR _pDrawItemInfo$[ebp]
	mov	ecx, DWORD PTR [eax+20]
	sub	ecx, DWORD PTR _Radius$[ebp]
	push	ecx
	mov	edx, DWORD PTR _pDrawItemInfo$[ebp]
	mov	eax, DWORD PTR [edx+16]
	mov	ecx, DWORD PTR _pDrawItemInfo$[ebp]
	add	eax, DWORD PTR [ecx+24]
	sar	eax, 1
	add	eax, 1
	push	eax
	mov	edx, DWORD PTR _pDrawItemInfo$[ebp]
	mov	eax, DWORD PTR [edx+12]
	add	eax, DWORD PTR _Radius$[ebp]
	push	eax
	call	_GUI_DrawGradientV
	add	esp, 24					; 00000018H
; Line 165
	jmp	$LN17@BUTTON_Dra
$LN7@BUTTON_Dra:
; Line 170
	mov	eax, DWORD PTR _pDrawItemInfo$[ebp]
	mov	ecx, DWORD PTR [eax]
	push	ecx
	call	_BUTTON_LockH
	add	esp, 4
	mov	DWORD PTR _pObj$[ebp], eax
; Line 171
	mov	eax, DWORD PTR _pDrawItemInfo$[ebp]
	cmp	DWORD PTR [eax+8], 0
	jne	SHORT $LN6@BUTTON_Dra
; Line 172
	mov	eax, DWORD PTR _pObj$[ebp]
	xor	ecx, ecx
	cmp	DWORD PTR [eax+112], 0
	setne	cl
	mov	DWORD PTR _BitmapIndex$[ebp], ecx
; Line 173
	jmp	SHORT $LN5@BUTTON_Dra
$LN6@BUTTON_Dra:
; Line 174
	mov	eax, DWORD PTR _pObj$[ebp]
	mov	ecx, DWORD PTR [eax+116]
	neg	ecx
	sbb	ecx, ecx
	and	ecx, 2
	mov	DWORD PTR _BitmapIndex$[ebp], ecx
$LN5@BUTTON_Dra:
; Line 176
	mov	eax, DWORD PTR _BitmapIndex$[ebp]
	mov	ecx, DWORD PTR _pObj$[ebp]
	mov	edx, DWORD PTR [ecx+eax*4+108]
	mov	DWORD PTR _hDrawObj$[ebp], edx
; Line 177
	call	_GUI_ALLOC_UnlockH
	mov	DWORD PTR _pObj$[ebp], 0
; Line 178
	push	0
	push	0
	mov	eax, DWORD PTR _pDrawItemInfo$[ebp]
	mov	ecx, DWORD PTR [eax]
	push	ecx
	mov	edx, DWORD PTR _hDrawObj$[ebp]
	push	edx
	call	_GUI_DRAW__Draw
	add	esp, 16					; 00000010H
; Line 179
	jmp	$LN17@BUTTON_Dra
$LN4@BUTTON_Dra:
; Line 184
	mov	eax, DWORD PTR _pDrawItemInfo$[ebp]
	mov	ecx, DWORD PTR [eax]
	push	ecx
	call	_BUTTON_LockH
	add	esp, 4
	mov	DWORD PTR _pObj$[ebp], eax
; Line 185
	mov	eax, DWORD PTR _pObj$[ebp]
	mov	ecx, DWORD PTR [eax+104]
	mov	DWORD PTR _hText$[ebp], ecx
; Line 186
	cmp	DWORD PTR _hText$[ebp], 0
	je	$LN3@BUTTON_Dra
; Line 190
	mov	eax, DWORD PTR _pObj$[ebp]
	movsx	ecx, WORD PTR [eax+96]
	mov	DWORD PTR _TextAlign$[ebp], ecx
; Line 193
	mov	eax, DWORD PTR _pDrawItemInfo$[ebp]
	cmp	DWORD PTR [eax+8], 0
	jne	SHORT $LN21@BUTTON_Dra
	mov	DWORD PTR tv290[ebp], 1
	jmp	SHORT $LN22@BUTTON_Dra
$LN21@BUTTON_Dra:
	mov	ecx, DWORD PTR _pDrawItemInfo$[ebp]
	mov	edx, DWORD PTR [ecx+8]
	sub	edx, 2
	neg	edx
	sbb	edx, edx
	and	edx, 2
	mov	DWORD PTR tv290[ebp], edx
$LN22@BUTTON_Dra:
	mov	eax, DWORD PTR tv290[ebp]
	mov	DWORD PTR _ColorIndex$[ebp], eax
; Line 194
	mov	eax, DWORD PTR _ColorIndex$[ebp]
	mov	ecx, DWORD PTR _pObj$[ebp]
	mov	edx, DWORD PTR [ecx+eax*4+68]
	mov	DWORD PTR _Color$[ebp], edx
; Line 195
	mov	eax, DWORD PTR _pObj$[ebp]
	mov	ecx, DWORD PTR [eax+88]
	push	ecx
	call	_GUI_SetFont
	add	esp, 4
; Line 196
	call	_GUI_ALLOC_UnlockH
	mov	DWORD PTR _pObj$[ebp], 0
; Line 197
	mov	eax, DWORD PTR _Color$[ebp]
	push	eax
	call	_GUI_SetColor
	add	esp, 4
; Line 201
	lea	eax, DWORD PTR _Rect$[ebp]
	push	eax
	call	_GUI_GetClientRect
	add	esp, 4
; Line 202
	movsx	eax, WORD PTR _Rect$[ebp]
	mov	ecx, DWORD PTR _pProps$[ebp]
	add	eax, DWORD PTR [ecx+28]
	mov	WORD PTR _Rect$[ebp], ax
; Line 203
	movsx	eax, WORD PTR _Rect$[ebp+4]
	mov	ecx, DWORD PTR _pProps$[ebp]
	sub	eax, DWORD PTR [ecx+28]
	mov	WORD PTR _Rect$[ebp+4], ax
; Line 204
	movsx	eax, WORD PTR _Rect$[ebp+2]
	add	eax, 2
	mov	WORD PTR _Rect$[ebp+2], ax
; Line 205
	movsx	eax, WORD PTR _Rect$[ebp+6]
	sub	eax, 2
	mov	WORD PTR _Rect$[ebp+6], ax
; Line 209
	push	2
	call	_GUI_SetTextMode
	add	esp, 4
; Line 210
	mov	eax, DWORD PTR _hText$[ebp]
	push	eax
	call	_GUI_ALLOC_LockH
	add	esp, 4
	mov	DWORD PTR _s$[ebp], eax
; Line 211
	mov	eax, DWORD PTR _TextAlign$[ebp]
	push	eax
	lea	ecx, DWORD PTR _Rect$[ebp]
	push	ecx
	mov	edx, DWORD PTR _s$[ebp]
	push	edx
	call	_GUI_DispStringInRect
	add	esp, 12					; 0000000cH
; Line 212
	call	_GUI_ALLOC_UnlockH
	mov	DWORD PTR _s$[ebp], 0
; Line 213
	jmp	SHORT $LN2@BUTTON_Dra
$LN3@BUTTON_Dra:
; Line 214
	call	_GUI_ALLOC_UnlockH
	mov	DWORD PTR _pObj$[ebp], 0
$LN2@BUTTON_Dra:
; Line 216
	jmp	SHORT $LN17@BUTTON_Dra
$LN1@BUTTON_Dra:
; Line 218
	mov	eax, DWORD PTR _pDrawItemInfo$[ebp]
	mov	ecx, DWORD PTR [eax]
	push	ecx
	call	_WM_SetHasTrans
	add	esp, 4
$LN17@BUTTON_Dra:
; Line 221
	xor	eax, eax
; Line 222
	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN26@BUTTON_Dra
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 344				; 00000158H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	npad	3
$LN26@BUTTON_Dra:
	DD	1
	DD	$LN25@BUTTON_Dra
$LN25@BUTTON_Dra:
	DD	-108					; ffffff94H
	DD	8
	DD	$LN24@BUTTON_Dra
$LN24@BUTTON_Dra:
	DB	82					; 00000052H
	DB	101					; 00000065H
	DB	99					; 00000063H
	DB	116					; 00000074H
	DB	0
	npad	3
$LN27@BUTTON_Dra:
	DD	$LN1@BUTTON_Dra
	DD	$LN16@BUTTON_Dra
	DD	$LN7@BUTTON_Dra
	DD	$LN4@BUTTON_Dra
	DD	$LN17@BUTTON_Dra
$LN23@BUTTON_Dra:
	DB	0
	DB	4
	DB	4
	DB	1
	DB	2
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	3
_BUTTON_DrawSkinFlex ENDP
_TEXT	ENDS
PUBLIC	_BUTTON_SetSkinFlexProps
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT _BUTTON_SetSkinFlexProps
_TEXT	SEGMENT
_pProps$ = 8						; size = 4
_Index$ = 12						; size = 4
_BUTTON_SetSkinFlexProps PROC				; COMDAT
; Line 228
	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 229
	cmp	DWORD PTR _Index$[ebp], 4
	jae	SHORT $LN2@BUTTON_Set
; Line 230
	mov	esi, DWORD PTR _pProps$[ebp]
	mov	eax, DWORD PTR _Index$[ebp]
	mov	edi, DWORD PTR __apProps[eax*4]
	mov	ecx, 8
	rep movsd
$LN2@BUTTON_Set:
; Line 232
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
_BUTTON_SetSkinFlexProps ENDP
_TEXT	ENDS
PUBLIC	_BUTTON_GetSkinFlexProps
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT _BUTTON_GetSkinFlexProps
_TEXT	SEGMENT
_pProps$ = 8						; size = 4
_Index$ = 12						; size = 4
_BUTTON_GetSkinFlexProps PROC				; COMDAT
; Line 238
	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 239
	cmp	DWORD PTR _Index$[ebp], 4
	jae	SHORT $LN2@BUTTON_Get
; Line 240
	mov	eax, DWORD PTR _Index$[ebp]
	mov	esi, DWORD PTR __apProps[eax*4]
	mov	ecx, 8
	mov	edi, DWORD PTR _pProps$[ebp]
	rep movsd
$LN2@BUTTON_Get:
; Line 242
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
_BUTTON_GetSkinFlexProps ENDP
_TEXT	ENDS
END
