; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	C:\DUII\Simulation\GUI\Widget\EDIT_SetInsertMode.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_EDIT_SetInsertMode
EXTRN	_GUI_ALLOC_UnlockH:PROC
EXTRN	_EDIT_LockH:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	__RTC_InitBase:PROC
;	COMDAT rtc$TMZ
; File c:\duii\simulation\gui\widget\edit_setinsertmode.c
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
; Function compile flags: /Odtp /RTCsu /ZI
rtc$IMZ	ENDS
;	COMDAT _EDIT_SetInsertMode
_TEXT	SEGMENT
_pObj$10557 = -20					; size = 4
_PrevMode$ = -8						; size = 4
_hObj$ = 8						; size = 4
_OnOff$ = 12						; size = 4
_EDIT_SetInsertMode PROC				; COMDAT
; Line 38
	push	ebp
	mov	ebp, esp
	sub	esp, 216				; 000000d8H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-216]
	mov	ecx, 54					; 00000036H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 39
	mov	DWORD PTR _PrevMode$[ebp], 0
; Line 40
	cmp	DWORD PTR _hObj$[ebp], 0
	je	SHORT $LN1@EDIT_SetIn
; Line 43
	mov	eax, DWORD PTR _hObj$[ebp]
	push	eax
	call	_EDIT_LockH
	add	esp, 4
	mov	DWORD PTR _pObj$10557[ebp], eax
; Line 44
	mov	eax, DWORD PTR _pObj$10557[ebp]
	movzx	ecx, BYTE PTR [eax+88]
	mov	DWORD PTR _PrevMode$[ebp], ecx
; Line 45
	xor	eax, eax
	cmp	DWORD PTR _OnOff$[ebp], 0
	sete	al
	mov	ecx, DWORD PTR _pObj$10557[ebp]
	mov	BYTE PTR [ecx+88], al
; Line 46
	call	_GUI_ALLOC_UnlockH
	mov	DWORD PTR _pObj$10557[ebp], 0
$LN1@EDIT_SetIn:
; Line 49
	mov	eax, DWORD PTR _PrevMode$[ebp]
; Line 50
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 216				; 000000d8H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
_EDIT_SetInsertMode ENDP
_TEXT	ENDS
END
