; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	C:\DUII\Simulation\GUI\Core\GUI_CalcColorDist.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_GUI_CalcColorDist
EXTRN	__RTC_Shutdown:PROC
EXTRN	__RTC_InitBase:PROC
;	COMDAT rtc$TMZ
; File c:\duii\simulation\gui\core\gui_calccolordist.c
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
; Function compile flags: /Odtp /RTCsu /ZI
rtc$IMZ	ENDS
;	COMDAT _GUI_CalcColorDist
_TEXT	SEGMENT
_Sum$ = -20						; size = 4
_Dist$ = -8						; size = 2
_PalColor$ = 8						; size = 4
_Color$ = 12						; size = 4
_GUI_CalcColorDist PROC					; COMDAT
; Line 65
	push	ebp
	mov	ebp, esp
	sub	esp, 216				; 000000d8H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-216]
	mov	ecx, 54					; 00000036H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 69
	mov	eax, DWORD PTR _PalColor$[ebp]
	and	eax, 255				; 000000ffH
	mov	ecx, DWORD PTR _Color$[ebp]
	and	ecx, 255				; 000000ffH
	sub	eax, ecx
	mov	WORD PTR _Dist$[ebp], ax
; Line 70
	movsx	eax, WORD PTR _Dist$[ebp]
	test	eax, eax
	jge	SHORT $LN3@GUI_CalcCo
; Line 71
	movsx	eax, WORD PTR _Dist$[ebp]
	neg	eax
	mov	WORD PTR _Dist$[ebp], ax
$LN3@GUI_CalcCo:
; Line 72
	movzx	eax, WORD PTR _Dist$[ebp]
	movzx	ecx, WORD PTR _Dist$[ebp]
	imul	eax, ecx
	mov	DWORD PTR _Sum$[ebp], eax
; Line 73
	mov	eax, DWORD PTR _PalColor$[ebp]
	shr	eax, 8
	and	eax, 255				; 000000ffH
	mov	ecx, DWORD PTR _Color$[ebp]
	shr	ecx, 8
	and	ecx, 255				; 000000ffH
	sub	eax, ecx
	mov	WORD PTR _Dist$[ebp], ax
; Line 74
	movsx	eax, WORD PTR _Dist$[ebp]
	test	eax, eax
	jge	SHORT $LN2@GUI_CalcCo
; Line 75
	movsx	eax, WORD PTR _Dist$[ebp]
	neg	eax
	mov	WORD PTR _Dist$[ebp], ax
$LN2@GUI_CalcCo:
; Line 76
	movzx	eax, WORD PTR _Dist$[ebp]
	movzx	ecx, WORD PTR _Dist$[ebp]
	imul	eax, ecx
	add	eax, DWORD PTR _Sum$[ebp]
	mov	DWORD PTR _Sum$[ebp], eax
; Line 77
	mov	eax, DWORD PTR _PalColor$[ebp]
	shr	eax, 16					; 00000010H
	mov	ecx, DWORD PTR _Color$[ebp]
	shr	ecx, 16					; 00000010H
	sub	eax, ecx
	mov	WORD PTR _Dist$[ebp], ax
; Line 78
	movsx	eax, WORD PTR _Dist$[ebp]
	test	eax, eax
	jge	SHORT $LN1@GUI_CalcCo
; Line 79
	movsx	eax, WORD PTR _Dist$[ebp]
	neg	eax
	mov	WORD PTR _Dist$[ebp], ax
$LN1@GUI_CalcCo:
; Line 80
	movzx	eax, WORD PTR _Dist$[ebp]
	movzx	ecx, WORD PTR _Dist$[ebp]
	imul	eax, ecx
	add	eax, DWORD PTR _Sum$[ebp]
; Line 81
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
_GUI_CalcColorDist ENDP
_TEXT	ENDS
END
