; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	C:\DUII\Simulation\GUI\Core\GUI_SIF_PropExtFrmInfo.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_GUI_SIF__ClearLine_ExtFrm
EXTRN	_GUI__CharHasTrans:BYTE
EXTRN	_LCD_FillRect:PROC
EXTRN	_GUI__Read16:PROC
EXTRN	_GUI_SIF__GetpCharInfo:PROC
EXTRN	_GUI_UC__GetCharCodeInc:PROC
EXTRN	_GUI_SetColor:PROC
EXTRN	_GUI_GetBkColor:PROC
EXTRN	_GUI_Context:BYTE
EXTRN	_GUI_GetColor:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	@_RTC_CheckStackVars@8:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	__RTC_InitBase:PROC
;	COMDAT rtc$TMZ
; File c:\duii\simulation\gui\core\gui_sif_propextfrminfo.c
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
; Function compile flags: /Odtp /RTCsu /ZI
rtc$IMZ	ENDS
;	COMDAT _GUI_SIF__ClearLine_ExtFrm
_TEXT	SEGMENT
tv75 = -280						; size = 4
_xSizeChar$8353 = -80					; size = 4
_xDistChar$8352 = -68					; size = 4
_OldColor$ = -56					; size = 4
_yDist$ = -44						; size = 4
_xDist$ = -32						; size = 4
_Char$ = -20						; size = 2
_pCharInfo$ = -8					; size = 4
_s$ = 8							; size = 4
_Len$ = 12						; size = 4
_GUI_SIF__ClearLine_ExtFrm PROC				; COMDAT
; Line 37
	push	ebp
	mov	ebp, esp
	sub	esp, 280				; 00000118H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-280]
	mov	ecx, 70					; 00000046H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 42
	call	_GUI_GetColor
	mov	DWORD PTR _OldColor$[ebp], eax
; Line 43
	mov	DWORD PTR _xDist$[ebp], 0
; Line 44
	mov	eax, DWORD PTR _GUI_Context+28
	movzx	ecx, BYTE PTR [eax+25]
	mov	edx, DWORD PTR _GUI_Context+28
	movzx	eax, BYTE PTR [edx+27]
	imul	ecx, eax
	mov	DWORD PTR _yDist$[ebp], ecx
; Line 45
	mov	DWORD PTR _pCharInfo$[ebp], 0
; Line 46
	movsx	eax, WORD PTR _GUI_Context+42
	and	eax, 4
	je	SHORT $LN9@GUI_SIF__C
	call	_GUI_GetColor
	mov	DWORD PTR tv75[ebp], eax
	jmp	SHORT $LN10@GUI_SIF__C
$LN9@GUI_SIF__C:
	call	_GUI_GetBkColor
	mov	DWORD PTR tv75[ebp], eax
$LN10@GUI_SIF__C:
	mov	ecx, DWORD PTR tv75[ebp]
	push	ecx
	call	_GUI_SetColor
	add	esp, 4
$LN6@GUI_SIF__C:
; Line 47
	mov	eax, DWORD PTR _Len$[ebp]
	sub	eax, 1
	mov	DWORD PTR _Len$[ebp], eax
	js	$LN5@GUI_SIF__C
; Line 48
	lea	eax, DWORD PTR _s$[ebp]
	push	eax
	call	_GUI_UC__GetCharCodeInc
	add	esp, 4
	mov	WORD PTR _Char$[ebp], ax
; Line 49
	push	16					; 00000010H
	movzx	eax, WORD PTR _Char$[ebp]
	push	eax
	mov	ecx, DWORD PTR _GUI_Context+28
	push	ecx
	call	_GUI_SIF__GetpCharInfo
	add	esp, 12					; 0000000cH
	mov	DWORD PTR _pCharInfo$[ebp], eax
; Line 50
	cmp	DWORD PTR _pCharInfo$[ebp], 0
	je	SHORT $LN4@GUI_SIF__C
; Line 51
	cmp	DWORD PTR _Len$[ebp], 0
	jne	SHORT $LN3@GUI_SIF__C
; Line 53
	lea	eax, DWORD PTR _pCharInfo$[ebp]
	push	eax
	call	_GUI__Read16
	add	esp, 4
	movzx	ecx, ax
	mov	DWORD PTR _xSizeChar$8353[ebp], ecx
; Line 54
	mov	eax, DWORD PTR _pCharInfo$[ebp]
	add	eax, 6
	mov	DWORD PTR _pCharInfo$[ebp], eax
; Line 55
	lea	eax, DWORD PTR _pCharInfo$[ebp]
	push	eax
	call	_GUI__Read16
	add	esp, 4
	movzx	ecx, ax
	mov	DWORD PTR _xDistChar$8352[ebp], ecx
; Line 56
	mov	eax, DWORD PTR _xDist$[ebp]
	add	eax, DWORD PTR _xDistChar$8352[ebp]
	mov	DWORD PTR _xDist$[ebp], eax
; Line 57
	mov	eax, DWORD PTR _xSizeChar$8353[ebp]
	cmp	eax, DWORD PTR _xDistChar$8352[ebp]
	jle	SHORT $LN2@GUI_SIF__C
; Line 58
	mov	eax, DWORD PTR _xSizeChar$8353[ebp]
	sub	eax, DWORD PTR _xDistChar$8352[ebp]
	add	eax, DWORD PTR _xDist$[ebp]
	mov	DWORD PTR _xDist$[ebp], eax
$LN2@GUI_SIF__C:
; Line 60
	jmp	SHORT $LN4@GUI_SIF__C
$LN3@GUI_SIF__C:
; Line 61
	mov	eax, DWORD PTR _pCharInfo$[ebp]
	add	eax, 8
	mov	DWORD PTR _pCharInfo$[ebp], eax
; Line 62
	lea	eax, DWORD PTR _pCharInfo$[ebp]
	push	eax
	call	_GUI__Read16
	add	esp, 4
	movzx	ecx, ax
	add	ecx, DWORD PTR _xDist$[ebp]
	mov	DWORD PTR _xDist$[ebp], ecx
$LN4@GUI_SIF__C:
; Line 65
	jmp	$LN6@GUI_SIF__C
$LN5@GUI_SIF__C:
; Line 66
	movsx	eax, WORD PTR _GUI_Context+36
	mov	ecx, DWORD PTR _yDist$[ebp]
	lea	edx, DWORD PTR [eax+ecx-1]
	push	edx
	movsx	eax, WORD PTR _GUI_Context+34
	mov	ecx, DWORD PTR _xDist$[ebp]
	lea	edx, DWORD PTR [eax+ecx-1]
	push	edx
	movsx	eax, WORD PTR _GUI_Context+36
	push	eax
	movsx	ecx, WORD PTR _GUI_Context+34
	push	ecx
	call	_LCD_FillRect
	add	esp, 16					; 00000010H
; Line 67
	mov	eax, DWORD PTR _OldColor$[ebp]
	push	eax
	call	_GUI_SetColor
	add	esp, 4
; Line 71
	mov	BYTE PTR _GUI__CharHasTrans, 1
; Line 72
	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN13@GUI_SIF__C
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 280				; 00000118H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	npad	3
$LN13@GUI_SIF__C:
	DD	1
	DD	$LN12@GUI_SIF__C
$LN12@GUI_SIF__C:
	DD	-8					; fffffff8H
	DD	4
	DD	$LN11@GUI_SIF__C
$LN11@GUI_SIF__C:
	DB	112					; 00000070H
	DB	67					; 00000043H
	DB	104					; 00000068H
	DB	97					; 00000061H
	DB	114					; 00000072H
	DB	73					; 00000049H
	DB	110					; 0000006eH
	DB	102					; 00000066H
	DB	111					; 0000006fH
	DB	0
_GUI_SIF__ClearLine_ExtFrm ENDP
_TEXT	ENDS
PUBLIC	_GUI_SIF__GetCharDistX_ExtFrm
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT _GUI_SIF__GetCharDistX_ExtFrm
_TEXT	SEGMENT
_DistX$ = -20						; size = 2
_pCharInfo$ = -8					; size = 4
_c$ = 8							; size = 2
_GUI_SIF__GetCharDistX_ExtFrm PROC			; COMDAT
; Line 78
	push	ebp
	mov	ebp, esp
	sub	esp, 216				; 000000d8H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-216]
	mov	ecx, 54					; 00000036H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 80
	xor	eax, eax
	mov	WORD PTR _DistX$[ebp], ax
; Line 81
	push	16					; 00000010H
	movzx	eax, WORD PTR _c$[ebp]
	push	eax
	mov	ecx, DWORD PTR _GUI_Context+28
	push	ecx
	call	_GUI_SIF__GetpCharInfo
	add	esp, 12					; 0000000cH
	mov	DWORD PTR _pCharInfo$[ebp], eax
; Line 82
	cmp	DWORD PTR _pCharInfo$[ebp], 0
	je	SHORT $LN1@GUI_SIF__G
; Line 83
	mov	eax, DWORD PTR _pCharInfo$[ebp]
	add	eax, 8
	mov	DWORD PTR _pCharInfo$[ebp], eax
; Line 84
	lea	eax, DWORD PTR _pCharInfo$[ebp]
	push	eax
	call	_GUI__Read16
	add	esp, 4
	mov	WORD PTR _DistX$[ebp], ax
$LN1@GUI_SIF__G:
; Line 86
	movsx	eax, WORD PTR _DistX$[ebp]
; Line 87
	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN6@GUI_SIF__G
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 216				; 000000d8H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	npad	3
$LN6@GUI_SIF__G:
	DD	1
	DD	$LN5@GUI_SIF__G
$LN5@GUI_SIF__G:
	DD	-8					; fffffff8H
	DD	4
	DD	$LN4@GUI_SIF__G
$LN4@GUI_SIF__G:
	DB	112					; 00000070H
	DB	67					; 00000043H
	DB	104					; 00000068H
	DB	97					; 00000061H
	DB	114					; 00000072H
	DB	73					; 00000049H
	DB	110					; 0000006eH
	DB	102					; 00000066H
	DB	111					; 0000006fH
	DB	0
_GUI_SIF__GetCharDistX_ExtFrm ENDP
_TEXT	ENDS
PUBLIC	_GUI_SIF__GetFontInfo_ExtFrm
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT _GUI_SIF__GetFontInfo_ExtFrm
_TEXT	SEGMENT
_pData$ = -8						; size = 4
_pFont$ = 8						; size = 4
_pfi$ = 12						; size = 4
_GUI_SIF__GetFontInfo_ExtFrm PROC			; COMDAT
; Line 93
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 95
	mov	eax, DWORD PTR _pFont$[ebp]
	mov	ecx, DWORD PTR [eax+28]
	add	ecx, 4
	mov	DWORD PTR _pData$[ebp], ecx
; Line 96
	lea	eax, DWORD PTR _pData$[ebp]
	push	eax
	call	_GUI__Read16
	add	esp, 4
	mov	ecx, DWORD PTR _pfi$[ebp]
	mov	BYTE PTR [ecx+2], al
; Line 97
	lea	eax, DWORD PTR _pData$[ebp]
	push	eax
	call	_GUI__Read16
	add	esp, 4
	mov	ecx, DWORD PTR _pfi$[ebp]
	mov	BYTE PTR [ecx+3], al
; Line 98
	lea	eax, DWORD PTR _pData$[ebp]
	push	eax
	call	_GUI__Read16
	add	esp, 4
	mov	ecx, DWORD PTR _pfi$[ebp]
	mov	BYTE PTR [ecx+4], al
; Line 99
	mov	eax, 1
	mov	ecx, DWORD PTR _pfi$[ebp]
	mov	WORD PTR [ecx], ax
; Line 100
	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN5@GUI_SIF__G@2
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
$LN5@GUI_SIF__G@2:
	DD	1
	DD	$LN4@GUI_SIF__G@2
$LN4@GUI_SIF__G@2:
	DD	-8					; fffffff8H
	DD	4
	DD	$LN3@GUI_SIF__G@2
$LN3@GUI_SIF__G@2:
	DB	112					; 00000070H
	DB	68					; 00000044H
	DB	97					; 00000061H
	DB	116					; 00000074H
	DB	97					; 00000061H
	DB	0
_GUI_SIF__GetFontInfo_ExtFrm ENDP
_TEXT	ENDS
PUBLIC	_GUI_SIF__IsInFont_ExtFrm
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT _GUI_SIF__IsInFont_ExtFrm
_TEXT	SEGMENT
_pCharInfo$ = -8					; size = 4
_pFont$ = 8						; size = 4
_c$ = 12						; size = 2
_GUI_SIF__IsInFont_ExtFrm PROC				; COMDAT
; Line 106
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 108
	mov	eax, DWORD PTR _pFont$[ebp]
	mov	DWORD PTR _pFont$[ebp], eax
; Line 109
	push	16					; 00000010H
	movzx	eax, WORD PTR _c$[ebp]
	push	eax
	mov	ecx, DWORD PTR _GUI_Context+28
	push	ecx
	call	_GUI_SIF__GetpCharInfo
	add	esp, 12					; 0000000cH
	mov	DWORD PTR _pCharInfo$[ebp], eax
; Line 110
	xor	eax, eax
	cmp	DWORD PTR _pCharInfo$[ebp], 0
	setne	al
; Line 111
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
_GUI_SIF__IsInFont_ExtFrm ENDP
_TEXT	ENDS
PUBLIC	_GUI_SIF__GetCharInfo_ExtFrm
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT _GUI_SIF__GetCharInfo_ExtFrm
_TEXT	SEGMENT
_pCharInfo$ = -8					; size = 4
_c$ = 8							; size = 2
_pInfo$ = 12						; size = 4
_GUI_SIF__GetCharInfo_ExtFrm PROC			; COMDAT
; Line 117
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 119
	push	16					; 00000010H
	movzx	eax, WORD PTR _c$[ebp]
	push	eax
	mov	ecx, DWORD PTR _GUI_Context+28
	push	ecx
	call	_GUI_SIF__GetpCharInfo
	add	esp, 12					; 0000000cH
	mov	DWORD PTR _pCharInfo$[ebp], eax
; Line 120
	cmp	DWORD PTR _pCharInfo$[ebp], 0
	je	SHORT $LN1@GUI_SIF__G@3
; Line 121
	lea	eax, DWORD PTR _pCharInfo$[ebp]
	push	eax
	call	_GUI__Read16
	add	esp, 4
	mov	ecx, DWORD PTR _pInfo$[ebp]
	mov	BYTE PTR [ecx], al
; Line 122
	mov	eax, DWORD PTR _pCharInfo$[ebp]
	add	eax, 6
	mov	DWORD PTR _pCharInfo$[ebp], eax
; Line 123
	lea	eax, DWORD PTR _pCharInfo$[ebp]
	push	eax
	call	_GUI__Read16
	add	esp, 4
	mov	ecx, DWORD PTR _pInfo$[ebp]
	mov	BYTE PTR [ecx+4], al
; Line 124
	xor	eax, eax
	jmp	SHORT $LN2@GUI_SIF__G@3
$LN1@GUI_SIF__G@3:
; Line 126
	mov	eax, 1
$LN2@GUI_SIF__G@3:
; Line 127
	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN6@GUI_SIF__G@3
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	npad	1
$LN6@GUI_SIF__G@3:
	DD	1
	DD	$LN5@GUI_SIF__G@3
$LN5@GUI_SIF__G@3:
	DD	-8					; fffffff8H
	DD	4
	DD	$LN4@GUI_SIF__G@3
$LN4@GUI_SIF__G@3:
	DB	112					; 00000070H
	DB	67					; 00000043H
	DB	104					; 00000068H
	DB	97					; 00000061H
	DB	114					; 00000072H
	DB	73					; 00000049H
	DB	110					; 0000006eH
	DB	102					; 00000066H
	DB	111					; 0000006fH
	DB	0
_GUI_SIF__GetCharInfo_ExtFrm ENDP
_TEXT	ENDS
END
