; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	C:\DUII\Simulation\GUI\Core\GUI_CursorArrowLI.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_GUI_BitmapArrowLI
PUBLIC	_GUI_CursorArrowLI
EXTRN	_GUI_CursorPalI:BYTE
EXTRN	_GUI_Pixels_ArrowL:BYTE
CONST	SEGMENT
_GUI_BitmapArrowLI DW 012H
	DW	01eH
	DW	05H
	DW	02H
	DD	FLAT:_GUI_Pixels_ArrowL
	DD	FLAT:_GUI_CursorPalI
	ORG $+4
_GUI_CursorArrowLI DD FLAT:_GUI_BitmapArrowLI
	DD	00H
	DD	00H
CONST	ENDS
END
