; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	C:\DUII\Simulation\GUI\Core\GUI_Realloc.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_GUI_ALLOC_Realloc
EXTRN	_GUI_ALLOC_Free:PROC
EXTRN	_memcpy:PROC
EXTRN	_GUI_ALLOC_h2p:PROC
EXTRN	_GUI_ALLOC_GetSize:PROC
EXTRN	_GUI_ALLOC_AllocNoInit:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	__RTC_InitBase:PROC
;	COMDAT rtc$TMZ
; File c:\duii\simulation\gui\core\gui_realloc.c
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
; Function compile flags: /Odtp /RTCsu /ZI
rtc$IMZ	ENDS
;	COMDAT _GUI_ALLOC_Realloc
_TEXT	SEGMENT
tv71 = -256						; size = 4
_OldSize$9170 = -56					; size = 4
_Size$9169 = -44					; size = 4
_pOld$9168 = -32					; size = 4
_pNew$9167 = -20					; size = 4
_hNew$ = -8						; size = 4
_hOld$ = 8						; size = 4
_NewSize$ = 12						; size = 4
_GUI_ALLOC_Realloc PROC					; COMDAT
; Line 52
	push	ebp
	mov	ebp, esp
	sub	esp, 256				; 00000100H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-256]
	mov	ecx, 64					; 00000040H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 54
	mov	eax, DWORD PTR _NewSize$[ebp]
	push	eax
	call	_GUI_ALLOC_AllocNoInit
	add	esp, 4
	mov	DWORD PTR _hNew$[ebp], eax
; Line 55
	cmp	DWORD PTR _hNew$[ebp], 0
	je	SHORT $LN1@GUI_ALLOC_
	cmp	DWORD PTR _hOld$[ebp], 0
	je	SHORT $LN1@GUI_ALLOC_
; Line 58
	mov	eax, DWORD PTR _hOld$[ebp]
	push	eax
	call	_GUI_ALLOC_GetSize
	add	esp, 4
	mov	DWORD PTR _OldSize$9170[ebp], eax
; Line 59
	mov	eax, DWORD PTR _OldSize$9170[ebp]
	cmp	eax, DWORD PTR _NewSize$[ebp]
	jge	SHORT $LN4@GUI_ALLOC_
	mov	ecx, DWORD PTR _OldSize$9170[ebp]
	mov	DWORD PTR tv71[ebp], ecx
	jmp	SHORT $LN5@GUI_ALLOC_
$LN4@GUI_ALLOC_:
	mov	edx, DWORD PTR _NewSize$[ebp]
	mov	DWORD PTR tv71[ebp], edx
$LN5@GUI_ALLOC_:
	mov	eax, DWORD PTR tv71[ebp]
	mov	DWORD PTR _Size$9169[ebp], eax
; Line 61
	mov	eax, DWORD PTR _hNew$[ebp]
	push	eax
	call	_GUI_ALLOC_h2p
	add	esp, 4
	mov	DWORD PTR _pNew$9167[ebp], eax
; Line 62
	mov	eax, DWORD PTR _hOld$[ebp]
	push	eax
	call	_GUI_ALLOC_h2p
	add	esp, 4
	mov	DWORD PTR _pOld$9168[ebp], eax
; Line 63
	mov	eax, DWORD PTR _Size$9169[ebp]
	push	eax
	mov	ecx, DWORD PTR _pOld$9168[ebp]
	push	ecx
	mov	edx, DWORD PTR _pNew$9167[ebp]
	push	edx
	call	_memcpy
	add	esp, 12					; 0000000cH
; Line 64
	mov	eax, DWORD PTR _hOld$[ebp]
	push	eax
	call	_GUI_ALLOC_Free
	add	esp, 4
$LN1@GUI_ALLOC_:
; Line 67
	mov	eax, DWORD PTR _hNew$[ebp]
; Line 68
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 256				; 00000100H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
_GUI_ALLOC_Realloc ENDP
_TEXT	ENDS
END
