; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	C:\DUII\Simulation\GUI\Core\GUI_CursorHeaderMI.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_GUI_CursorHeaderMI
EXTRN	_GUI_CursorPalI:BYTE
EXTRN	_GUI_PixelsHeaderM:BYTE
CONST	SEGMENT
__Bitmap DW	011H
	DW	011H
	DW	05H
	DW	02H
	DD	FLAT:_GUI_PixelsHeaderM
	DD	FLAT:_GUI_CursorPalI
	ORG $+4
_GUI_CursorHeaderMI DD FLAT:__Bitmap
	DD	08H
	DD	08H
CONST	ENDS
END
