; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	C:\DUII\Simulation\GUI\Core\GUI_PolyMagnify.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_GUI_MagnifyPolygon
EXTRN	__RTC_Shutdown:PROC
EXTRN	__RTC_InitBase:PROC
;	COMDAT rtc$TMZ
; File c:\duii\simulation\gui\core\gui_polymagnify.c
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
; Function compile flags: /Odtp /RTCsu /ZI
rtc$IMZ	ENDS
;	COMDAT _GUI_MagnifyPolygon
_TEXT	SEGMENT
_j$ = -8						; size = 4
_pDest$ = 8						; size = 4
_pSrc$ = 12						; size = 4
_NumPoints$ = 16					; size = 4
_Mag$ = 20						; size = 4
_GUI_MagnifyPolygon PROC				; COMDAT
; Line 35
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 37
	mov	DWORD PTR _j$[ebp], 0
	jmp	SHORT $LN3@GUI_Magnif
$LN2@GUI_Magnif:
	mov	eax, DWORD PTR _j$[ebp]
	add	eax, 1
	mov	DWORD PTR _j$[ebp], eax
$LN3@GUI_Magnif:
	mov	eax, DWORD PTR _j$[ebp]
	cmp	eax, DWORD PTR _NumPoints$[ebp]
	jge	SHORT $LN4@GUI_Magnif
; Line 38
	mov	eax, DWORD PTR _j$[ebp]
	mov	ecx, DWORD PTR _pSrc$[ebp]
	movsx	edx, WORD PTR [ecx+eax*4]
	imul	edx, DWORD PTR _Mag$[ebp]
	mov	eax, DWORD PTR _j$[ebp]
	mov	ecx, DWORD PTR _pDest$[ebp]
	mov	WORD PTR [ecx+eax*4], dx
; Line 39
	mov	eax, DWORD PTR _j$[ebp]
	mov	ecx, DWORD PTR _pSrc$[ebp]
	movsx	edx, WORD PTR [ecx+eax*4+2]
	imul	edx, DWORD PTR _Mag$[ebp]
	mov	eax, DWORD PTR _j$[ebp]
	mov	ecx, DWORD PTR _pDest$[ebp]
	mov	WORD PTR [ecx+eax*4+2], dx
; Line 40
	jmp	SHORT $LN2@GUI_Magnif
$LN4@GUI_Magnif:
; Line 41
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
_GUI_MagnifyPolygon ENDP
_TEXT	ENDS
END
