; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	C:\DUII\Simulation\GUI\Core\GUI_CursorCrossM.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_GUI_BitmapCrossM
PUBLIC	_GUI_CursorCrossM
EXTRN	_GUI_CursorPal:BYTE
EXTRN	_GUI_Pixels_CrossM:BYTE
CONST	SEGMENT
_GUI_BitmapCrossM DW 015H
	DW	015H
	DW	06H
	DW	02H
	DD	FLAT:_GUI_Pixels_CrossM
	DD	FLAT:_GUI_CursorPal
	ORG $+4
_GUI_CursorCrossM DD FLAT:_GUI_BitmapCrossM
	DD	0aH
	DD	0aH
CONST	ENDS
END
