; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	C:\DUII\Simulation\GUI\ConvertColor\GUICC_222.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_LCD_API_ColorConv_222
PUBLIC	_LCD_API_ColorConv_M222
CONST	SEGMENT
_LCD_API_ColorConv_222 DD FLAT:__Color2Index_222
	DD	FLAT:__Index2Color_222
	DD	FLAT:__GetIndexMask_222
_LCD_API_ColorConv_M222 DD FLAT:__Color2Index_M222
	DD	FLAT:__Index2Color_M222
	DD	FLAT:__GetIndexMask_M222
CONST	ENDS
EXTRN	__RTC_Shutdown:PROC
EXTRN	__RTC_InitBase:PROC
;	COMDAT rtc$TMZ
; File c:\duii\simulation\gui\convertcolor\guicc_222.c
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
; Function compile flags: /Odtp /RTCsu /ZI
rtc$IMZ	ENDS
;	COMDAT __Color2Index_222
_TEXT	SEGMENT
_b$ = -32						; size = 4
_g$ = -20						; size = 4
_r$ = -8						; size = 4
_Color$ = 8						; size = 4
__Color2Index_222 PROC					; COMDAT
; Line 35
	push	ebp
	mov	ebp, esp
	sub	esp, 228				; 000000e4H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-228]
	mov	ecx, 57					; 00000039H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 37
	mov	eax, DWORD PTR _Color$[ebp]
	and	eax, 255				; 000000ffH
	add	eax, 42					; 0000002aH
	xor	edx, edx
	mov	ecx, 85					; 00000055H
	div	ecx
	mov	DWORD PTR _r$[ebp], eax
; Line 38
	mov	eax, DWORD PTR _Color$[ebp]
	shr	eax, 8
	and	eax, 255				; 000000ffH
	add	eax, 42					; 0000002aH
	xor	edx, edx
	mov	ecx, 85					; 00000055H
	div	ecx
	mov	DWORD PTR _g$[ebp], eax
; Line 39
	mov	eax, DWORD PTR _Color$[ebp]
	shr	eax, 16					; 00000010H
	and	eax, 255				; 000000ffH
	add	eax, 42					; 0000002aH
	xor	edx, edx
	mov	ecx, 85					; 00000055H
	div	ecx
	mov	DWORD PTR _b$[ebp], eax
; Line 40
	mov	eax, DWORD PTR _g$[ebp]
	mov	ecx, DWORD PTR _r$[ebp]
	lea	eax, DWORD PTR [ecx+eax*4]
	mov	edx, DWORD PTR _b$[ebp]
	shl	edx, 4
	add	eax, edx
; Line 41
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
__Color2Index_222 ENDP
; Function compile flags: /Odtp /RTCsu /ZI
_TEXT	ENDS
;	COMDAT __Index2Color_222
_TEXT	SEGMENT
_b$ = -32						; size = 2
_g$ = -20						; size = 2
_r$ = -8						; size = 2
_Index$ = 8						; size = 4
__Index2Color_222 PROC					; COMDAT
; Line 47
	push	ebp
	mov	ebp, esp
	sub	esp, 228				; 000000e4H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-228]
	mov	ecx, 57					; 00000039H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 49
	mov	eax, DWORD PTR _Index$[ebp]
	and	eax, 3
	imul	eax, 85					; 00000055H
	mov	WORD PTR _r$[ebp], ax
; Line 50
	mov	eax, DWORD PTR _Index$[ebp]
	shr	eax, 2
	and	eax, 3
	imul	eax, 85					; 00000055H
	mov	WORD PTR _g$[ebp], ax
; Line 51
	mov	eax, DWORD PTR _Index$[ebp]
	shr	eax, 4
	imul	eax, 85					; 00000055H
	mov	WORD PTR _b$[ebp], ax
; Line 52
	movzx	eax, WORD PTR _b$[ebp]
	shl	eax, 16					; 00000010H
	movzx	ecx, WORD PTR _g$[ebp]
	shl	ecx, 8
	or	eax, ecx
	movzx	edx, WORD PTR _r$[ebp]
	or	eax, edx
; Line 53
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
__Index2Color_222 ENDP
; Function compile flags: /Odtp /RTCsu /ZI
_TEXT	ENDS
;	COMDAT __GetIndexMask_222
_TEXT	SEGMENT
__GetIndexMask_222 PROC					; COMDAT
; Line 59
	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 60
	mov	eax, 63					; 0000003fH
; Line 61
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
__GetIndexMask_222 ENDP
; Function compile flags: /Odtp /RTCsu /ZI
_TEXT	ENDS
;	COMDAT __Color2Index_M222
_TEXT	SEGMENT
_b$ = -32						; size = 4
_g$ = -20						; size = 4
_r$ = -8						; size = 4
_Color$ = 8						; size = 4
__Color2Index_M222 PROC					; COMDAT
; Line 93
	push	ebp
	mov	ebp, esp
	sub	esp, 228				; 000000e4H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-228]
	mov	ecx, 57					; 00000039H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 95
	mov	eax, DWORD PTR _Color$[ebp]
	and	eax, 255				; 000000ffH
	add	eax, 42					; 0000002aH
	xor	edx, edx
	mov	ecx, 85					; 00000055H
	div	ecx
	mov	DWORD PTR _r$[ebp], eax
; Line 96
	mov	eax, DWORD PTR _Color$[ebp]
	shr	eax, 8
	and	eax, 255				; 000000ffH
	add	eax, 42					; 0000002aH
	xor	edx, edx
	mov	ecx, 85					; 00000055H
	div	ecx
	mov	DWORD PTR _g$[ebp], eax
; Line 97
	mov	eax, DWORD PTR _Color$[ebp]
	shr	eax, 16					; 00000010H
	and	eax, 255				; 000000ffH
	add	eax, 42					; 0000002aH
	xor	edx, edx
	mov	ecx, 85					; 00000055H
	div	ecx
	mov	DWORD PTR _b$[ebp], eax
; Line 98
	mov	eax, DWORD PTR _g$[ebp]
	mov	ecx, DWORD PTR _b$[ebp]
	lea	eax, DWORD PTR [ecx+eax*4]
	mov	edx, DWORD PTR _r$[ebp]
	shl	edx, 4
	add	eax, edx
; Line 99
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
__Color2Index_M222 ENDP
; Function compile flags: /Odtp /RTCsu /ZI
_TEXT	ENDS
;	COMDAT __Index2Color_M222
_TEXT	SEGMENT
_b$ = -32						; size = 2
_g$ = -20						; size = 2
_r$ = -8						; size = 2
_Index$ = 8						; size = 4
__Index2Color_M222 PROC					; COMDAT
; Line 105
	push	ebp
	mov	ebp, esp
	sub	esp, 228				; 000000e4H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-228]
	mov	ecx, 57					; 00000039H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 107
	mov	eax, DWORD PTR _Index$[ebp]
	and	eax, 3
	imul	eax, 85					; 00000055H
	mov	WORD PTR _r$[ebp], ax
; Line 108
	mov	eax, DWORD PTR _Index$[ebp]
	shr	eax, 2
	and	eax, 3
	imul	eax, 85					; 00000055H
	mov	WORD PTR _g$[ebp], ax
; Line 109
	mov	eax, DWORD PTR _Index$[ebp]
	shr	eax, 4
	imul	eax, 85					; 00000055H
	mov	WORD PTR _b$[ebp], ax
; Line 110
	movzx	eax, WORD PTR _r$[ebp]
	shl	eax, 16					; 00000010H
	movzx	ecx, WORD PTR _g$[ebp]
	shl	ecx, 8
	or	eax, ecx
	movzx	edx, WORD PTR _b$[ebp]
	or	eax, edx
; Line 111
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
__Index2Color_M222 ENDP
; Function compile flags: /Odtp /RTCsu /ZI
_TEXT	ENDS
;	COMDAT __GetIndexMask_M222
_TEXT	SEGMENT
__GetIndexMask_M222 PROC				; COMDAT
; Line 117
	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 118
	mov	eax, 63					; 0000003fH
; Line 119
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
__GetIndexMask_M222 ENDP
_TEXT	ENDS
END
