; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	C:\DUII\Simulation\GUI\MemDev\GUIDEV_ReduceYSize.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_GUI_MEMDEV_ReduceYSize
EXTRN	_GUI_ALLOC_h2p:PROC
EXTRN	_GUI_Context:BYTE
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	__RTC_InitBase:PROC
;	COMDAT rtc$TMZ
; File c:\duii\simulation\gui\memdev\guidev_reduceysize.c
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
; Function compile flags: /Odtp /RTCsu /ZI
rtc$IMZ	ENDS
;	COMDAT _GUI_MEMDEV_ReduceYSize
_TEXT	SEGMENT
_pDevData$9167 = -8					; size = 4
_hMem$ = 8						; size = 4
_YSize$ = 12						; size = 4
_GUI_MEMDEV_ReduceYSize PROC				; COMDAT
; Line 41
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 43
	cmp	DWORD PTR _hMem$[ebp], 0
	jne	SHORT $LN3@GUI_MEMDEV
; Line 44
	mov	eax, DWORD PTR _GUI_Context+76
	mov	DWORD PTR _hMem$[ebp], eax
$LN3@GUI_MEMDEV:
; Line 45
	cmp	DWORD PTR _hMem$[ebp], 0
	jne	SHORT $LN2@GUI_MEMDEV
; Line 46
	jmp	SHORT $LN4@GUI_MEMDEV
$LN2@GUI_MEMDEV:
; Line 50
	mov	eax, DWORD PTR _hMem$[ebp]
	push	eax
	call	_GUI_ALLOC_h2p
	add	esp, 4
	mov	DWORD PTR _pDevData$9167[ebp], eax
; Line 51
	mov	eax, DWORD PTR _pDevData$9167[ebp]
	movsx	ecx, WORD PTR [eax+10]
	cmp	DWORD PTR _YSize$[ebp], ecx
	jge	SHORT $LN4@GUI_MEMDEV
; Line 52
	mov	eax, DWORD PTR _pDevData$9167[ebp]
	mov	cx, WORD PTR _YSize$[ebp]
	mov	WORD PTR [eax+10], cx
$LN4@GUI_MEMDEV:
; Line 56
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
_GUI_MEMDEV_ReduceYSize ENDP
_TEXT	ENDS
END
