; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	C:\DUII\Simulation\GUI\Widget\HEADER_Bitmap.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_HEADER_SetBitmapEx
EXTRN	_WM_InvalidateWindow:PROC
EXTRN	_HEADER__SetDrawObj:PROC
EXTRN	_GUI_DRAW_BITMAP_Create:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	__RTC_InitBase:PROC
;	COMDAT rtc$TMZ
; File c:\duii\simulation\gui\widget\header_bitmap.c
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
; Function compile flags: /Odtp /RTCsu /ZI
rtc$IMZ	ENDS
;	COMDAT _HEADER_SetBitmapEx
_TEXT	SEGMENT
_hObj$ = 8						; size = 4
_Index$ = 12						; size = 4
_pBitmap$ = 16						; size = 4
_x$ = 20						; size = 4
_y$ = 24						; size = 4
_HEADER_SetBitmapEx PROC				; COMDAT
; Line 38
	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 39
	mov	eax, DWORD PTR _y$[ebp]
	push	eax
	mov	ecx, DWORD PTR _x$[ebp]
	push	ecx
	mov	edx, DWORD PTR _pBitmap$[ebp]
	push	edx
	call	_GUI_DRAW_BITMAP_Create
	add	esp, 12					; 0000000cH
	push	eax
	mov	eax, DWORD PTR _Index$[ebp]
	push	eax
	mov	ecx, DWORD PTR _hObj$[ebp]
	push	ecx
	call	_HEADER__SetDrawObj
	add	esp, 12					; 0000000cH
; Line 40
	mov	eax, DWORD PTR _hObj$[ebp]
	push	eax
	call	_WM_InvalidateWindow
	add	esp, 4
; Line 41
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 192				; 000000c0H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
_HEADER_SetBitmapEx ENDP
_TEXT	ENDS
PUBLIC	_HEADER_SetBitmap
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT _HEADER_SetBitmap
_TEXT	SEGMENT
_hObj$ = 8						; size = 4
_Index$ = 12						; size = 4
_pBitmap$ = 16						; size = 4
_HEADER_SetBitmap PROC					; COMDAT
; Line 47
	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	mov	ecx, 48					; 00000030H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 48
	push	0
	push	0
	mov	eax, DWORD PTR _pBitmap$[ebp]
	push	eax
	mov	ecx, DWORD PTR _Index$[ebp]
	push	ecx
	mov	edx, DWORD PTR _hObj$[ebp]
	push	edx
	call	_HEADER_SetBitmapEx
	add	esp, 20					; 00000014H
; Line 49
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 192				; 000000c0H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
_HEADER_SetBitmap ENDP
_TEXT	ENDS
END
