; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	C:\DUII\Simulation\GUI\Core\LCD_GetNumDisplays.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_LCD_GetNumLayers
EXTRN	_GUI_DEVICE__GetpDriver:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	__RTC_InitBase:PROC
;	COMDAT rtc$TMZ
; File c:\duii\simulation\gui\core\lcd_getnumdisplays.c
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
; Function compile flags: /Odtp /RTCsu /ZI
rtc$IMZ	ENDS
;	COMDAT _LCD_GetNumLayers
_TEXT	SEGMENT
_NumLayers$ = -20					; size = 4
_i$ = -8						; size = 4
_LCD_GetNumLayers PROC					; COMDAT
; Line 35
	push	ebp
	mov	ebp, esp
	sub	esp, 216				; 000000d8H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-216]
	mov	ecx, 54					; 00000036H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 38
	mov	DWORD PTR _NumLayers$[ebp], 0
; Line 39
	mov	DWORD PTR _i$[ebp], 0
	jmp	SHORT $LN4@LCD_GetNum
$LN3@LCD_GetNum:
	mov	eax, DWORD PTR _i$[ebp]
	add	eax, 1
	mov	DWORD PTR _i$[ebp], eax
$LN4@LCD_GetNum:
	cmp	DWORD PTR _i$[ebp], 1
	jge	SHORT $LN2@LCD_GetNum
; Line 40
	mov	eax, DWORD PTR _i$[ebp]
	push	eax
	call	_GUI_DEVICE__GetpDriver
	add	esp, 4
	test	eax, eax
	je	SHORT $LN1@LCD_GetNum
; Line 41
	mov	eax, DWORD PTR _NumLayers$[ebp]
	add	eax, 1
	mov	DWORD PTR _NumLayers$[ebp], eax
$LN1@LCD_GetNum:
; Line 43
	jmp	SHORT $LN3@LCD_GetNum
$LN2@LCD_GetNum:
; Line 44
	mov	eax, DWORD PTR _NumLayers$[ebp]
; Line 45
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 216				; 000000d8H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
_LCD_GetNumLayers ENDP
_TEXT	ENDS
END
