; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	C:\DUII\Simulation\GUI\Widget\LISTBOX_ScrollStep.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_LISTBOX_SetScrollStepH
EXTRN	_GUI_ALLOC_UnlockH:PROC
EXTRN	_LISTBOX_LockH:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	__RTC_InitBase:PROC
;	COMDAT rtc$TMZ
; File c:\duii\simulation\gui\widget\listbox_scrollstep.c
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
; Function compile flags: /Odtp /RTCsu /ZI
rtc$IMZ	ENDS
;	COMDAT _LISTBOX_SetScrollStepH
_TEXT	SEGMENT
_pObj$11918 = -8					; size = 4
_hObj$ = 8						; size = 4
_Value$ = 12						; size = 4
_LISTBOX_SetScrollStepH PROC				; COMDAT
; Line 36
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 37
	cmp	DWORD PTR _hObj$[ebp], 0
	je	SHORT $LN2@LISTBOX_Se
; Line 40
	mov	eax, DWORD PTR _hObj$[ebp]
	push	eax
	call	_LISTBOX_LockH
	add	esp, 4
	mov	DWORD PTR _pObj$11918[ebp], eax
; Line 41
	mov	eax, DWORD PTR _pObj$11918[ebp]
	mov	cx, WORD PTR _Value$[ebp]
	mov	WORD PTR [eax+92], cx
; Line 42
	call	_GUI_ALLOC_UnlockH
	mov	DWORD PTR _pObj$11918[ebp], 0
$LN2@LISTBOX_Se:
; Line 45
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
_LISTBOX_SetScrollStepH ENDP
_TEXT	ENDS
PUBLIC	_LISTBOX_GetScrollStepH
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT _LISTBOX_GetScrollStepH
_TEXT	SEGMENT
_pObj$11925 = -20					; size = 4
_Value$ = -8						; size = 4
_hObj$ = 8						; size = 4
_LISTBOX_GetScrollStepH PROC				; COMDAT
; Line 51
	push	ebp
	mov	ebp, esp
	sub	esp, 216				; 000000d8H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-216]
	mov	ecx, 54					; 00000036H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 52
	mov	DWORD PTR _Value$[ebp], 0
; Line 53
	cmp	DWORD PTR _hObj$[ebp], 0
	je	SHORT $LN1@LISTBOX_Ge
; Line 56
	mov	eax, DWORD PTR _hObj$[ebp]
	push	eax
	call	_LISTBOX_LockH
	add	esp, 4
	mov	DWORD PTR _pObj$11925[ebp], eax
; Line 57
	mov	eax, DWORD PTR _pObj$11925[ebp]
	movzx	ecx, WORD PTR [eax+92]
	mov	DWORD PTR _Value$[ebp], ecx
; Line 58
	call	_GUI_ALLOC_UnlockH
	mov	DWORD PTR _pObj$11925[ebp], 0
$LN1@LISTBOX_Ge:
; Line 61
	mov	eax, DWORD PTR _Value$[ebp]
; Line 62
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 216				; 000000d8H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
_LISTBOX_GetScrollStepH ENDP
_TEXT	ENDS
END
