; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	C:\DUII\Simulation\GUI\Widget\MENU_InsertItem.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_MENU_InsertItem
EXTRN	_MENU__ResizeMenu:PROC
EXTRN	_GUI_ARRAY_DeleteItem:PROC
EXTRN	_MENU__SetItem:PROC
EXTRN	_GUI_ARRAY_InsertBlankItem:PROC
EXTRN	_GUI_ALLOC_UnlockH:PROC
EXTRN	_MENU_LockH:PROC
EXTRN	_MENU__FindItem:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	__RTC_InitBase:PROC
;	COMDAT rtc$TMZ
; File c:\duii\simulation\gui\widget\menu_insertitem.c
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
; Function compile flags: /Odtp /RTCsu /ZI
rtc$IMZ	ENDS
;	COMDAT _MENU_InsertItem
_TEXT	SEGMENT
_ItemArray$10537 = -32					; size = 4
_pObj$10536 = -20					; size = 4
_Index$10534 = -8					; size = 4
_hObj$ = 8						; size = 4
_ItemId$ = 12						; size = 2
_pItemData$ = 16					; size = 4
_MENU_InsertItem PROC					; COMDAT
; Line 38
	push	ebp
	mov	ebp, esp
	sub	esp, 228				; 000000e4H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-228]
	mov	ecx, 57					; 00000039H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 39
	cmp	DWORD PTR _hObj$[ebp], 0
	je	$LN6@MENU_Inser
	cmp	DWORD PTR _pItemData$[ebp], 0
	je	$LN6@MENU_Inser
; Line 42
	lea	eax, DWORD PTR _hObj$[ebp]
	push	eax
	movzx	ecx, WORD PTR _ItemId$[ebp]
	push	ecx
	mov	edx, DWORD PTR _hObj$[ebp]
	push	edx
	call	_MENU__FindItem
	add	esp, 12					; 0000000cH
	mov	DWORD PTR _Index$10534[ebp], eax
; Line 43
	cmp	DWORD PTR _Index$10534[ebp], 0
	jl	SHORT $LN6@MENU_Inser
; Line 46
	mov	eax, DWORD PTR _hObj$[ebp]
	push	eax
	call	_MENU_LockH
	add	esp, 4
	mov	DWORD PTR _pObj$10536[ebp], eax
; Line 47
	mov	eax, DWORD PTR _pObj$10536[ebp]
	mov	ecx, DWORD PTR [eax+104]
	mov	DWORD PTR _ItemArray$10537[ebp], ecx
; Line 48
	call	_GUI_ALLOC_UnlockH
	mov	DWORD PTR _pObj$10536[ebp], 0
; Line 49
	mov	eax, DWORD PTR _Index$10534[ebp]
	push	eax
	mov	ecx, DWORD PTR _ItemArray$10537[ebp]
	push	ecx
	call	_GUI_ARRAY_InsertBlankItem
	add	esp, 8
	movzx	edx, al
	test	edx, edx
	je	SHORT $LN6@MENU_Inser
; Line 50
	mov	eax, DWORD PTR _pItemData$[ebp]
	push	eax
	mov	ecx, DWORD PTR _Index$10534[ebp]
	push	ecx
	mov	edx, DWORD PTR _hObj$[ebp]
	push	edx
	call	_MENU__SetItem
	add	esp, 12					; 0000000cH
	movzx	eax, al
	test	eax, eax
	jne	SHORT $LN2@MENU_Inser
; Line 51
	mov	eax, DWORD PTR _Index$10534[ebp]
	push	eax
	mov	ecx, DWORD PTR _ItemArray$10537[ebp]
	push	ecx
	call	_GUI_ARRAY_DeleteItem
	add	esp, 8
; Line 52
	jmp	SHORT $LN6@MENU_Inser
$LN2@MENU_Inser:
; Line 53
	mov	eax, DWORD PTR _hObj$[ebp]
	push	eax
	call	_MENU__ResizeMenu
	add	esp, 4
$LN6@MENU_Inser:
; Line 59
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 228				; 000000e4H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
_MENU_InsertItem ENDP
_TEXT	ENDS
END
