; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	C:\DUII\Simulation\GUI\WM\WM__GetFocussedChild.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_WM__GetFocussedChild
EXTRN	_WM__IsChild:PROC
EXTRN	_WM__ahWinFocus:DWORD
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	__RTC_InitBase:PROC
;	COMDAT rtc$TMZ
; File c:\duii\simulation\gui\wm\wm__getfocussedchild.c
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
; Function compile flags: /Odtp /RTCsu /ZI
rtc$IMZ	ENDS
;	COMDAT _WM__GetFocussedChild
_TEXT	SEGMENT
_r$ = -8						; size = 4
_hWin$ = 8						; size = 4
_WM__GetFocussedChild PROC				; COMDAT
; Line 37
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 38
	mov	DWORD PTR _r$[ebp], 0
; Line 39
	mov	eax, DWORD PTR _hWin$[ebp]
	push	eax
	mov	ecx, DWORD PTR _WM__ahWinFocus
	push	ecx
	call	_WM__IsChild
	add	esp, 8
	test	eax, eax
	je	SHORT $LN1@WM__GetFoc
; Line 40
	mov	eax, DWORD PTR _WM__ahWinFocus
	mov	DWORD PTR _r$[ebp], eax
$LN1@WM__GetFoc:
; Line 42
	mov	eax, DWORD PTR _r$[ebp]
; Line 43
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
_WM__GetFocussedChild ENDP
_TEXT	ENDS
END
