; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	C:\DUII\Simulation\GUI\WM\WM_InvalidateArea.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_WM_InvalidateArea
EXTRN	_WM__Invalidate1Abs:PROC
EXTRN	_GUI_ALLOC_h2p:PROC
EXTRN	_WM__FirstWin:DWORD
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	__RTC_InitBase:PROC
;	COMDAT rtc$TMZ
; File c:\duii\simulation\gui\wm\wm_invalidatearea.c
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
; Function compile flags: /Odtp /RTCsu /ZI
rtc$IMZ	ENDS
;	COMDAT _WM_InvalidateArea
_TEXT	SEGMENT
_hWin$ = -8						; size = 4
_pRect$ = 8						; size = 4
_WM_InvalidateArea PROC					; COMDAT
; Line 42
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 46
	mov	eax, DWORD PTR _WM__FirstWin
	mov	DWORD PTR _hWin$[ebp], eax
	jmp	SHORT $LN3@WM_Invalid
$LN2@WM_Invalid:
	mov	eax, DWORD PTR _hWin$[ebp]
	push	eax
	call	_GUI_ALLOC_h2p
	add	esp, 4
	mov	ecx, DWORD PTR [eax+20]
	mov	DWORD PTR _hWin$[ebp], ecx
$LN3@WM_Invalid:
	cmp	DWORD PTR _hWin$[ebp], 0
	je	SHORT $LN4@WM_Invalid
; Line 47
	mov	eax, DWORD PTR _pRect$[ebp]
	push	eax
	mov	ecx, DWORD PTR _hWin$[ebp]
	push	ecx
	call	_WM__Invalidate1Abs
	add	esp, 8
; Line 48
	jmp	SHORT $LN2@WM_Invalid
$LN4@WM_Invalid:
; Line 50
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
_WM_InvalidateArea ENDP
_TEXT	ENDS
END
