; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	C:\DUII\Simulation\GUI\WM\WM_SetScrollState.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_WM_SetScrollState
EXTRN	_WM_SendMessage:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	@_RTC_CheckStackVars@8:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	__RTC_InitBase:PROC
;	COMDAT rtc$TMZ
; File c:\duii\simulation\gui\wm\wm_setscrollstate.c
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
; Function compile flags: /Odtp /RTCsu /ZI
rtc$IMZ	ENDS
;	COMDAT _WM_SetScrollState
_TEXT	SEGMENT
_Msg$9437 = -20						; size = 16
_hWin$ = 8						; size = 4
_pState$ = 12						; size = 4
_WM_SetScrollState PROC					; COMDAT
; Line 37
	push	ebp
	mov	ebp, esp
	sub	esp, 216				; 000000d8H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-216]
	mov	ecx, 54					; 00000036H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 38
	cmp	DWORD PTR _hWin$[ebp], 0
	je	SHORT $LN2@WM_SetScro
	cmp	DWORD PTR _pState$[ebp], 0
	je	SHORT $LN2@WM_SetScro
; Line 40
	mov	DWORD PTR _Msg$9437[ebp], 36		; 00000024H
; Line 41
	mov	eax, DWORD PTR _pState$[ebp]
	mov	DWORD PTR _Msg$9437[ebp+12], eax
; Line 42
	lea	eax, DWORD PTR _Msg$9437[ebp]
	push	eax
	mov	ecx, DWORD PTR _hWin$[ebp]
	push	ecx
	call	_WM_SendMessage
	add	esp, 8
$LN2@WM_SetScro:
; Line 44
	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN6@WM_SetScro
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 216				; 000000d8H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
$LN6@WM_SetScro:
	DD	1
	DD	$LN5@WM_SetScro
$LN5@WM_SetScro:
	DD	-20					; ffffffecH
	DD	16					; 00000010H
	DD	$LN4@WM_SetScro
$LN4@WM_SetScro:
	DB	77					; 0000004dH
	DB	115					; 00000073H
	DB	103					; 00000067H
	DB	0
_WM_SetScrollState ENDP
_TEXT	ENDS
END
