type A.txt >>upper.txt
type B.txt >>upper.txt
type C.txt >>upper.txt
type D.txt >>upper.txt
type E.txt >>upper.txt
type F.txt >>upper.txt
type G.txt >>upper.txt
type H.txt >>upper.txt
type I.txt >>upper.txt
type J.txt >>upper.txt
type K.txt >>upper.txt
type L.txt >>upper.txt
type M.txt >>upper.txt
type N.txt >>upper.txt
type O.txt >>upper.txt
type P.txt >>upper.txt
type Q.txt >>upper.txt
type R.txt >>upper.txt
type S.txt >>upper.txt
type T.txt >>upper.txt
type U.txt >>upper.txt
type V.txt >>upper.txt
type W.txt >>upper.txt
type X.txt >>upper.txt
type Y.txt >>upper.txt
type Z.txt >>upper.txt
