@ECHO OFF
ECHO CCDisplayDriver.BAT:  Compiling GUI\DisplayDriver
CALL CC GUIDRV_Template
CALL CC GUIDRV_Win32
CALL CC GUIDRV_Lin_1
CALL CC GUIDRV_Lin_16
CALL CC GUIDRV_Lin_2
CALL CC GUIDRV_Lin_24
CALL CC GUIDRV_Lin_32
CALL CC GUIDRV_Lin_4
CALL CC GUIDRV_Lin_8
CALL CC GUIDRV_Lin_OSX_16
CALL CC GUIDRV_Lin_OSX_24
CALL CC GUIDRV_Lin_OSX_32
CALL CC GUIDRV_Lin_OSY_16
CALL CC GUIDRV_Lin_OSY_24
CALL CC GUIDRV_Lin_OSY_32
CALL CC GUIDRV_Lin_OS_16
CALL CC GUIDRV_Lin_OS_24
CALL CC GUIDRV_Lin_OS_32
CALL CC GUIDRV_Lin_OX_16
CALL CC GUIDRV_Lin_OX_24
CALL CC GUIDRV_Lin_OX_32
CALL CC GUIDRV_Lin_OY_16
CALL CC GUIDRV_Lin_OY_24
CALL CC GUIDRV_Lin_OY_32
