/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
**********************************************************************
*                                                                    *
*        (c) 1996 - 2010  SEGGER Microcontroller GmbH & Co. KG       *
*                                                                    *
*        Internet: www.segger.com    Support:  support@segger.com    *
*                                                                    *
**********************************************************************

** emWin V5.06 - Graphical user interface for embedded applications **
emWin is protected by international copyright laws.   Knowledge of the
source code may not be used to write a similar product.  This file may
only be used in accordance with a license and should not be re-
distributed in any way. We appreciate your understanding and fairness.
----------------------------------------------------------------------
File        : F20B_1.C
Purpose     : ISO 8859-1, West European Character Set, bold
Height      : 20
---------------------------END-OF-HEADER------------------------------
*/

#include "GUI_FontIntern.h"

/* Start of unicode area <Latin-1 Supplement> */
GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00A0[ 20] = { /* code 00A0, NO-BREAK SPACE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00A1[ 20] = { /* code 00A1, INVERTED EXCLAMATION MARK */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  _XXX____,
  _XXX____,
  ________,
  __X_____,
  __X_____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00A2[ 40] = { /* code 00A2, CENT SIGN */
  ________,________,
  ________,________,
  ________,________,
  ________,X_______,
  _______X,________,
  _______X,________,
  ___XXXXX,________,
  __XXXXXX,X_______,
  _XXXX_XX,XX______,
  _XXX__X_,________,
  _XXX_X__,________,
  _XXX_X__,________,
  _XXX_X_X,XX______,
  _XXXX__X,XX______,
  __XXXXXX,X_______,
  ___XXXXX,________,
  ___X____,________,
  ___X____,________,
  ___X____,________,
  __X_____,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00A3[ 40] = { /* code 00A3, POUND SIGN */
  ________,________,
  ________,________,
  ________,________,
  ___XXXX_,________,
  __XXXXXX,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX____,________,
  XXXXXXX_,________,
  XXXXXXX_,________,
  __XXX___,________,
  __XXX___,________,
  _XXX____,________,
  XXXXXX__,X_______,
  XXXXXXXX,XX______,
  _X___XXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00A4[ 40] = { /* code 00A4, CURRENCY SIGN */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __X____X,________,
  _XXXXXXX,X_______,
  XXXXXXXX,XX______,
  _XXX__XX,X_______,
  _XX____X,X_______,
  _XX____X,X_______,
  _XXX__XX,X_______,
  XXXXXXXX,XX______,
  _XXXXXXX,X_______,
  __X____X,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00A5[ 40] = { /* code 00A5, YEN SIGN */
  ________,________,
  ________,________,
  ________,________,
  XXX_____,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  __XXX_XX,X_______,
  __XXX_XX,X_______,
  ___XXXXX,________,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  ____XXX_,________,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  ____XXX_,________,
  ____XXX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00A6[ 20] = { /* code 00A6, BROKEN BAR */
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00A7[ 40] = { /* code 00A7, SECTION SIGN */
  ________,________,
  ________,________,
  ________,________,
  __XXXX__,________,
  _XXXXXX_,________,
  _XX___XX,________,
  _XX_____,________,
  __XXX___,________,
  _XXXXXX_,________,
  XX__XXXX,________,
  XX____XX,X_______,
  XXX____X,X_______,
  _XXX___X,X_______,
  __XXXXXX,________,
  ___XXXX_,________,
  _____XXX,________,
  _XX___XX,________,
  _XXX__XX,________,
  __XXXXXX,________,
  ___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00A8[ 20] = { /* code 00A8, DIAERESIS */
  ________,
  ________,
  ________,
  XX__XX__,
  XX__XX__,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00A9[ 40] = { /* code 00A9, COPYRIGHT SIGN */
  ________,________,
  ________,________,
  ________,________,
  ____XXXX,X_______,
  __XX____,_XX_____,
  _XX_____,__XX____,
  _X___XXX,X__X____,
  X___XX__,XX__X___,
  X__XX___,____X___,
  X__XX___,____X___,
  X__XX___,____X___,
  X___XX__,XX__X___,
  _X___XXX,X__X____,
  _XX_____,__XX____,
  __XX____,_XX_____,
  ____XXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00AA[ 20] = { /* code 00AA, FEMININE ORDINAL INDICATOR */
  ________,
  ________,
  ________,
  _XXXX___,
  XX__XX__,
  ____XX__,
  _XXXXX__,
  XX__XX__,
  XX__XX__,
  _XXXXX__,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00AB[ 40] = { /* code 00AB, LEFT-POINTING DOUBLE ANGLE QUOTATION MARK */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XX__X,X_______,
  __XX__XX,________,
  _XXX_XXX,________,
  XXX_XXX_,________,
  XXX_XXX_,________,
  _XXX_XXX,________,
  __XX__XX,________,
  ___XX__X,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00AC[ 40] = { /* code 00AC, NOT SIGN */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  _______X,XX______,
  _______X,XX______,
  _______X,XX______,
  _______X,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00AD[ 20] = { /* code 00AD, SOFT HYPHEN */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00AE[ 40] = { /* code 00AE, REGISTERED SIGN */
  ________,________,
  ________,________,
  ________,________,
  ____XXXX,X_______,
  __XX____,_XX_____,
  _XX_____,__XX____,
  _X__XXXX,___X____,
  X___X___,X___X___,
  X___X___,X___X___,
  X___XXXX,____X___,
  X___X__X,____X___,
  X___X___,X___X___,
  _X__X___,X__X____,
  _XX_____,__XX____,
  __XX____,_XX_____,
  ____XXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00AF[ 40] = { /* code 00AF, MACRON */
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00B0[ 20] = { /* code 00B0, DEGREE SIGN */
  ________,
  ________,
  ________,
  __XXX___,
  _X___X__,
  _X___X__,
  _X___X__,
  __XXX___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00B1[ 40] = { /* code 00B1, PLUS-MINUS SIGN */
  ________,________,
  ________,________,
  ________,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ________,________,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00B2[ 20] = { /* code 00B2, SUPERSCRIPT TWO */
  ________,
  ________,
  ________,
  _XXX____,
  XX_XX___,
  ___XX___,
  __XXX___,
  _XXX____,
  XXX_____,
  XXXXX___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00B3[ 20] = { /* code 00B3, SUPERSCRIPT THREE */
  ________,
  ________,
  ________,
  _XXX____,
  XX_XX___,
  ___XX___,
  __XX____,
  ___XX___,
  XX_XX___,
  _XXX____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00B4[ 20] = { /* code 00B4, ACUTE ACCENT */
  ________,
  ________,
  ________,
  ___XXX__,
  ___XX___,
  __XX____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00B5[ 40] = { /* code 00B5, MICRO SIGN */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXXXXXX,X_______,
  _XXXXXXX,X_______,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00B6[ 40] = { /* code 00B6, PILCROW SIGN */
  ________,________,
  ________,________,
  ________,________,
  __XXXXXX,XX______,
  _XXXXXXX,XX______,
  XXXXXX_X,X_______,
  XXXXXX_X,X_______,
  XXXXXX_X,X_______,
  _XXXXX_X,X_______,
  __XXXX_X,X_______,
  ____XX_X,X_______,
  ____XX_X,X_______,
  ____XX_X,X_______,
  ____XX_X,X_______,
  ____XX_X,X_______,
  ____XX_X,X_______,
  ____XX_X,X_______,
  ____XX_X,X_______,
  ____XX_X,X_______,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00B7[ 20] = { /* code 00B7, MIDDLE DOT */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  _XXX____,
  _XXX____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00B8[ 20] = { /* code 00B8, CEDILLA */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  ___XX___,
  XXXX____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00B9[ 20] = { /* code 00B9, SUPERSCRIPT ONE */
  ________,
  ________,
  ________,
  __XX____,
  _XXX____,
  XXXX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00BA[ 20] = { /* code 00BA, MASCULINE ORDINAL INDICATOR */
  ________,
  ________,
  ________,
  __XXXX__,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  _XX__XX_,
  __XXXX__,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00BB[ 40] = { /* code 00BB, RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XX__XX_,________,
  __XX__XX,________,
  __XXX_XX,X_______,
  ___XXX_X,XX______,
  ___XXX_X,XX______,
  __XXX_XX,X_______,
  __XX__XX,________,
  _XX__XX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00BC[ 40] = { /* code 00BC, VULGAR FRACTION ONE QUARTER */
  ________,________,
  ________,________,
  ________,________,
  ___XX___,_XX_____,
  __XXX___,_XX_____,
  _XXXX___,XX______,
  ___XX___,XX______,
  ___XX__X,X_______,
  ___XX__X,X_______,
  ___XX_XX,____XX__,
  ______XX,___XXX__,
  _____XX_,___XXX__,
  _____XX_,__X_XX__,
  ____XX__,_X__XX__,
  ____XX__,_XXXXXX_,
  ___XX___,____XX__,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00BD[ 40] = { /* code 00BD, VULGAR FRACTION ONE HALF */
  ________,________,
  ________,________,
  ________,________,
  __XX____,_XX_____,
  _XXX____,_XX_____,
  XXXX____,XX______,
  __XX___X,XX______,
  __XX___X,X_______,
  __XX__XX,________,
  __XX__XX,__XXX___,
  _____XX_,_XX_XX__,
  _____XX_,____XX__,
  ____XX__,___XXX__,
  ___XX___,__XXX___,
  ___XX___,_XXX____,
  __XX____,_XXXXX__,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00BE[ 40] = { /* code 00BE, VULGAR FRACTION THREE QUARTERS */
  ________,________,
  ________,________,
  ________,________,
  _XXX____,__XX____,
  XX_XX___,_XX_____,
  ___XX___,_XX_____,
  __XX____,XX______,
  ___XX__X,X_______,
  XX_XX__X,X_______,
  _XXX__XX,____XX__,
  ______XX,___XXX__,
  _____XX_,___XXX__,
  ____XX__,__X_XX__,
  ____XX__,_X__XX__,
  ___XX___,_XXXXXX_,
  ___XX___,____XX__,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00BF[ 40] = { /* code 00BF, INVERTED QUESTION MARK */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ________,________,
  ____XXX_,________,
  ____XXX_,________,
  ___XXXX_,________,
  __XXXX__,________,
  _XXXX___,________,
  _XXX____,________,
  _XXX___X,XX______,
  _XXX__XX,XX______,
  __XXXXXX,X_______,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00C0[ 40] = { /* code 00C0, LATIN CAPITAL LETTER A WITH GRAVE */
  ____XXX_,________,
  _____XX_,________,
  ______XX,________,
  ____XXXX,X_______,
  ____XXXX,X_______,
  ____XXXX,X_______,
  ___XXX_X,XX______,
  ___XXX_X,XX______,
  ___XXX_X,XX______,
  __XXX___,XXX_____,
  __XXXXXX,XXX_____,
  __XXXXXX,XXX_____,
  _XXXXXXX,XXXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  XXX_____,__XXX___,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00C1[ 40] = { /* code 00C1, LATIN CAPITAL LETTER A WITH ACUTE */
  ______XX,X_______,
  ______XX,________,
  _____XX_,________,
  ____XXXX,X_______,
  ____XXXX,X_______,
  ____XXXX,X_______,
  ___XXX_X,XX______,
  ___XXX_X,XX______,
  ___XXX_X,XX______,
  __XXX___,XXX_____,
  __XXXXXX,XXX_____,
  __XXXXXX,XXX_____,
  _XXXXXXX,XXXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  XXX_____,__XXX___,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00C2[ 40] = { /* code 00C2, LATIN CAPITAL LETTER A WITH CIRCUMFLEX */
  _____XXX,________,
  ____XX_X,X_______,
  ________,________,
  ____XXXX,X_______,
  ____XXXX,X_______,
  ____XXXX,X_______,
  ___XXX_X,XX______,
  ___XXX_X,XX______,
  ___XXX_X,XX______,
  __XXX___,XXX_____,
  __XXXXXX,XXX_____,
  __XXXXXX,XXX_____,
  _XXXXXXX,XXXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  XXX_____,__XXX___,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00C3[ 40] = { /* code 00C3, LATIN CAPITAL LETTER A WITH TILDE */
  ____XXX_,_X______,
  ____X__X,XX______,
  ________,________,
  ____XXXX,X_______,
  ____XXXX,X_______,
  ____XXXX,X_______,
  ___XXX_X,XX______,
  ___XXX_X,XX______,
  ___XXX_X,XX______,
  __XXX___,XXX_____,
  __XXXXXX,XXX_____,
  __XXXXXX,XXX_____,
  _XXXXXXX,XXXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  XXX_____,__XXX___,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00C4[ 40] = { /* code 00C4, LATIN CAPITAL LETTER A WITH DIAERESIS */
  ____XX__,XX______,
  ____XX__,XX______,
  ________,________,
  ____XXXX,X_______,
  ____XXXX,X_______,
  ____XXXX,X_______,
  ___XXX_X,XX______,
  ___XXX_X,XX______,
  ___XXX_X,XX______,
  __XXX___,XXX_____,
  __XXXXXX,XXX_____,
  __XXXXXX,XXX_____,
  _XXXXXXX,XXXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  XXX_____,__XXX___,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00C5[ 40] = { /* code 00C5, LATIN CAPITAL LETTER A WITH RING ABOVE */
  ______XX,________,
  _____X__,X_______,
  _____X__,X_______,
  ____XXXX,X_______,
  ____XXXX,X_______,
  ____XXXX,X_______,
  ___XXX_X,XX______,
  ___XXX_X,XX______,
  ___XXX_X,XX______,
  __XXX___,XXX_____,
  __XXXXXX,XXX_____,
  __XXXXXX,XXX_____,
  _XXXXXXX,XXXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  XXX_____,__XXX___,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00C6[ 60] = { /* code 00C6, LATIN CAPITAL LETTER AE */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _____XXX,XXXXXXXX,X_______,
  ____XXXX,XXXXXXXX,X_______,
  ____XXX_,XXXXXXXX,X_______,
  ___XXX__,XXX_____,________,
  ___XXX__,XXX_____,________,
  __XXX___,XXXXXXXX,X_______,
  __XXX___,XXXXXXXX,X_______,
  __XXXXXX,XXXXXXXX,X_______,
  _XXXXXXX,XXX_____,________,
  _XXXXXXX,XXX_____,________,
  XXX_____,XXXXXXXX,X_______,
  XXX_____,XXXXXXXX,X_______,
  XX______,XXXXXXXX,X_______,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00C7[ 40] = { /* code 00C7, LATIN CAPITAL LETTER C WITH CEDILLA */
  ________,________,
  ________,________,
  ________,________,
  _____XXX,X_______,
  ___XXXXX,XXX_____,
  __XXXXXX,XXX_____,
  __XXX___,XXXX____,
  _XXX____,_XX_____,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,_XX_____,
  __XXX___,XXXX____,
  __XXXXXX,XXX_____,
  ___XXXXX,XXX_____,
  _____XXX,X_______,
  _____XXX,X_______,
  _______X,X_______,
  ____XXXX,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00C8[ 40] = { /* code 00C8, LATIN CAPITAL LETTER E WITH GRAVE */
  ____XXX_,________,
  _____XX_,________,
  ______XX,________,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXX____,________,
  _XXX____,________,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXX____,________,
  _XXX____,________,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00C9[ 40] = { /* code 00C9, LATIN CAPITAL LETTER E WITH ACUTE */
  ______XX,X_______,
  ______XX,________,
  _____XX_,________,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXX____,________,
  _XXX____,________,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXX____,________,
  _XXX____,________,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00CA[ 40] = { /* code 00CA, LATIN CAPITAL LETTER E WITH CIRCUMFLEX */
  _____XXX,________,
  ____XX_X,X_______,
  ________,________,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXX____,________,
  _XXX____,________,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXX____,________,
  _XXX____,________,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00CB[ 40] = { /* code 00CB, LATIN CAPITAL LETTER E WITH DIAERESIS */
  ___XX__X,X_______,
  ___XX__X,X_______,
  ________,________,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXX____,________,
  _XXX____,________,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXX____,________,
  _XXX____,________,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00CC[ 20] = { /* code 00CC, LATIN CAPITAL LETTER I WITH GRAVE */
  XXX_____,
  _XXX____,
  __XX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00CD[ 20] = { /* code 00CD, LATIN CAPITAL LETTER I WITH ACUTE */
  __XXX___,
  __XX____,
  _XX_____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00CE[ 20] = { /* code 00CE, LATIN CAPITAL LETTER I WITH CIRCUMFLEX */
  _XXX____,
  XX_XX___,
  ________,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00CF[ 20] = { /* code 00CF, LATIN CAPITAL LETTER I WITH DIAERESIS */
  XX_XX___,
  XX_XX___,
  ________,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00D0[ 40] = { /* code 00D0, LATIN CAPITAL LETTER ETH */
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,X_______,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXX____,XXXX____,
  _XXX____,_XXX____,
  XXXXXXX_,_XXX____,
  XXXXXXX_,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,XXXX____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00D1[ 40] = { /* code 00D1, LATIN CAPITAL LETTER N WITH TILDE */
  ____XXX_,_X______,
  ____X__X,XX______,
  ________,________,
  _XXX____,_XXX____,
  _XXXX___,_XXX____,
  _XXXXX__,_XXX____,
  _XXXXX__,_XXX____,
  _XXXXXX_,_XXX____,
  _XXX_XX_,_XXX____,
  _XXX_XXX,_XXX____,
  _XXX__XX,_XXX____,
  _XXX__XX,XXXX____,
  _XXX___X,XXXX____,
  _XXX___X,XXXX____,
  _XXX____,XXXX____,
  _XXX____,_XXX____,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00D2[ 40] = { /* code 00D2, LATIN CAPITAL LETTER O WITH GRAVE */
  _____XXX,________,
  ______XX,________,
  _______X,X_______,
  _____XXX,X_______,
  ___XXXXX,XXX_____,
  __XXXXXX,XXXX____,
  __XXX___,_XXX____,
  _XXX____,__XXX___,
  _XXX____,__XXX___,
  _XXX____,__XXX___,
  _XXX____,__XXX___,
  _XXX____,__XXX___,
  __XXX___,_XXX____,
  __XXXXXX,XXXX____,
  ___XXXXX,XXX_____,
  _____XXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00D3[ 40] = { /* code 00D3, LATIN CAPITAL LETTER O WITH ACUTE */
  ______XX,X_______,
  ______XX,________,
  _____XX_,________,
  _____XXX,X_______,
  ___XXXXX,XXX_____,
  __XXXXXX,XXXX____,
  __XXX___,_XXX____,
  _XXX____,__XXX___,
  _XXX____,__XXX___,
  _XXX____,__XXX___,
  _XXX____,__XXX___,
  _XXX____,__XXX___,
  __XXX___,_XXX____,
  __XXXXXX,XXXX____,
  ___XXXXX,XXX_____,
  _____XXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00D4[ 40] = { /* code 00D4, LATIN CAPITAL LETTER O WITH CIRCUMFLEX */
  ______XX,X_______,
  _____XX_,XX______,
  ________,________,
  _____XXX,X_______,
  ___XXXXX,XXX_____,
  __XXXXXX,XXXX____,
  __XXX___,_XXX____,
  _XXX____,__XXX___,
  _XXX____,__XXX___,
  _XXX____,__XXX___,
  _XXX____,__XXX___,
  _XXX____,__XXX___,
  __XXX___,_XXX____,
  __XXXXXX,XXXX____,
  ___XXXXX,XXX_____,
  _____XXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00D5[ 40] = { /* code 00D5, LATIN CAPITAL LETTER O WITH TILDE */
  ____XXX_,_X______,
  ____X__X,XX______,
  ________,________,
  _____XXX,X_______,
  ___XXXXX,XXX_____,
  __XXXXXX,XXXX____,
  __XXX___,_XXX____,
  _XXX____,__XXX___,
  _XXX____,__XXX___,
  _XXX____,__XXX___,
  _XXX____,__XXX___,
  _XXX____,__XXX___,
  __XXX___,_XXX____,
  __XXXXXX,XXXX____,
  ___XXXXX,XXX_____,
  _____XXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00D6[ 40] = { /* code 00D6, LATIN CAPITAL LETTER O WITH DIAERESIS */
  ____XX__,XX______,
  ____XX__,XX______,
  ________,________,
  _____XXX,X_______,
  ___XXXXX,XXX_____,
  __XXXXXX,XXXX____,
  __XXX___,_XXX____,
  _XXX____,__XXX___,
  _XXX____,__XXX___,
  _XXX____,__XXX___,
  _XXX____,__XXX___,
  _XXX____,__XXX___,
  __XXX___,_XXX____,
  __XXXXXX,XXXX____,
  ___XXXXX,XXX_____,
  _____XXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00D7[ 40] = { /* code 00D7, MULTIPLICATION SIGN */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __X____X,________,
  _XXX__XX,X_______,
  __XXXXXX,________,
  ___XXXX_,________,
  ___XXXX_,________,
  __XXXXXX,________,
  _XXX__XX,X_______,
  __X____X,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00D8[ 40] = { /* code 00D8, LATIN CAPITAL LETTER O WITH STROKE */
  ________,________,
  ________,________,
  ________,____X___,
  ____XXXX,XX__XX__,
  ___XXXXX,XXXXX___,
  __XXXXXX,XXXX____,
  __XXX___,_XXXX___,
  _XXX____,XXXXX___,
  _XXX___X,X_XXX___,
  _XXX__XX,__XXX___,
  _XXX_XX_,__XXX___,
  _XXXXX__,__XXX___,
  _XXXX___,_XXX____,
  __XXXXXX,XXXX____,
  _XXXXXXX,XXX_____,
  XX__XXXX,XX______,
  _X______,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00D9[ 40] = { /* code 00D9, LATIN CAPITAL LETTER U WITH GRAVE */
  ____XXX_,________,
  _____XX_,________,
  ______XX,________,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXXX___,XXXX____,
  __XXXXXX,XXX_____,
  __XXXXXX,XXX_____,
  ____XXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00DA[ 40] = { /* code 00DA, LATIN CAPITAL LETTER U WITH ACUTE */
  ______XX,X_______,
  ______XX,________,
  _____XX_,________,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXXX___,XXXX____,
  __XXXXXX,XXX_____,
  __XXXXXX,XXX_____,
  ____XXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00DB[ 40] = { /* code 00DB, LATIN CAPITAL LETTER U WITH CIRCUMFLEX */
  _____XXX,________,
  ____XX_X,X_______,
  ________,________,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXXX___,XXXX____,
  __XXXXXX,XXX_____,
  __XXXXXX,XXX_____,
  ____XXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00DC[ 40] = { /* code 00DC, LATIN CAPITAL LETTER U WITH DIAERESIS */
  ____XX__,XX______,
  ____XX__,XX______,
  ________,________,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXXX___,XXXX____,
  __XXXXXX,XXX_____,
  __XXXXXX,XXX_____,
  ____XXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00DD[ 40] = { /* code 00DD, LATIN CAPITAL LETTER Y WITH ACUTE */
  ______XX,X_______,
  ______XX,________,
  _____XX_,________,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  __XXX___,XXX_____,
  ___XXX_X,XX______,
  ___XXX_X,XX______,
  ____XXXX,X_______,
  ____XXXX,X_______,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00DE[ 40] = { /* code 00DE, LATIN CAPITAL LETTER THORN */
  ________,________,
  ________,________,
  ________,________,
  _XXX____,________,
  _XXX____,________,
  _XXXXXXX,X_______,
  _XXXXXXX,XX______,
  _XXXXXXX,XXX_____,
  _XXX____,XXX_____,
  _XXX____,XXX_____,
  _XXX____,XXX_____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XX______,
  _XXXXXXX,X_______,
  _XXX____,________,
  _XXX____,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00DF[ 40] = { /* code 00DF, LATIN SMALL LETTER SHARP S */
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,________,
  __XXXXXX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX_XXX,________,
  _XXX_XXX,________,
  _XXX_XXX,X_______,
  _XXX__XX,XX______,
  _XXX___X,XX______,
  _XXX____,XXX_____,
  _XXX_X__,XXX_____,
  _XXXXXXX,XXX_____,
  _XXX_XXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00E0[ 40] = { /* code 00E0, LATIN SMALL LETTER A WITH GRAVE */
  ________,________,
  ________,________,
  ___XXX__,________,
  ____XX__,________,
  _____XX_,________,
  ________,________,
  ___XXXXX,________,
  __XXXXXX,X_______,
  _XX___XX,X_______,
  _____XXX,X_______,
  ___XXXXX,X_______,
  __XXX_XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXXXXXX,X_______,
  __XXXX_X,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00E1[ 40] = { /* code 00E1, LATIN SMALL LETTER A WITH ACUTE */
  ________,________,
  ________,________,
  _____XXX,________,
  _____XX_,________,
  ____XX__,________,
  ________,________,
  ___XXXXX,________,
  __XXXXXX,X_______,
  _XX___XX,X_______,
  _____XXX,X_______,
  ___XXXXX,X_______,
  __XXX_XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXXXXXX,X_______,
  __XXXX_X,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00E2[ 40] = { /* code 00E2, LATIN SMALL LETTER A WITH CIRCUMFLEX */
  ________,________,
  ________,________,
  ________,________,
  ____XXX_,________,
  ___XX_XX,________,
  ________,________,
  ___XXXXX,________,
  __XXXXXX,X_______,
  _XX___XX,X_______,
  _____XXX,X_______,
  ___XXXXX,X_______,
  __XXX_XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXXXXXX,X_______,
  __XXXX_X,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00E3[ 40] = { /* code 00E3, LATIN SMALL LETTER A WITH TILDE */
  ________,________,
  ________,________,
  ________,________,
  __XXX__X,________,
  __X__XXX,________,
  ________,________,
  ___XXXXX,________,
  __XXXXXX,X_______,
  _XX___XX,X_______,
  _____XXX,X_______,
  ___XXXXX,X_______,
  __XXX_XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXXXXXX,X_______,
  __XXXX_X,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00E4[ 40] = { /* code 00E4, LATIN SMALL LETTER A WITH DIAERESIS */
  ________,________,
  ________,________,
  ________,________,
  __XX__XX,________,
  __XX__XX,________,
  ________,________,
  ___XXXXX,________,
  __XXXXXX,X_______,
  _XX___XX,X_______,
  _____XXX,X_______,
  ___XXXXX,X_______,
  __XXX_XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXXXXXX,X_______,
  __XXXX_X,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00E5[ 40] = { /* code 00E5, LATIN SMALL LETTER A WITH RING ABOVE */
  ________,________,
  ____XX__,________,
  ___X__X_,________,
  ___X__X_,________,
  ____XX__,________,
  ________,________,
  ___XXXXX,________,
  __XXXXXX,X_______,
  _XX___XX,X_______,
  _____XXX,X_______,
  ___XXXXX,X_______,
  __XXX_XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXXXXXX,X_______,
  __XXXX_X,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00E6[ 40] = { /* code 00E6, LATIN SMALL LETTER AE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXX_,_XXXX___,
  __XXXXXX,XXXXXX__,
  _XX___XX,X___XXX_,
  _____XXX,X___XXX_,
  ____XXXX,XXXXXXX_,
  __XXX_XX,XXXXXXX_,
  _XXX__XX,X_______,
  _XXX__XX,XX__XXX_,
  _XXXXXXX,XXXXXX__,
  __XXXX__,_XXXX___,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00E7[ 40] = { /* code 00E7, LATIN SMALL LETTER C WITH CEDILLA */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXX_,________,
  __XXXXXX,________,
  _XXXX_XX,X_______,
  _XXX___X,________,
  _XXX____,________,
  _XXX____,________,
  _XXX___X,________,
  _XXXX_XX,X_______,
  __XXXXXX,________,
  ___XXXX_,________,
  ___XXXX_,________,
  _____XX_,________,
  __XXXX__,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00E8[ 40] = { /* code 00E8, LATIN SMALL LETTER E WITH GRAVE */
  ________,________,
  ________,________,
  ____XXX_,________,
  _____XX_,________,
  ______XX,________,
  ________,________,
  ___XXXXX,________,
  __XXXXXX,X_______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  _XXX____,________,
  _XXX___X,XX______,
  __XXXXXX,X_______,
  ___XXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00E9[ 40] = { /* code 00E9, LATIN SMALL LETTER E WITH ACUTE */
  ________,________,
  ________,________,
  _____XXX,________,
  _____XX_,________,
  ____XX__,________,
  ________,________,
  ___XXXXX,________,
  __XXXXXX,X_______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  _XXX____,________,
  _XXX___X,XX______,
  __XXXXXX,X_______,
  ___XXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00EA[ 40] = { /* code 00EA, LATIN SMALL LETTER E WITH CIRCUMFLEX */
  ________,________,
  ________,________,
  ________,________,
  ____XXX_,________,
  ___XX_XX,________,
  ________,________,
  ___XXXXX,________,
  __XXXXXX,X_______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  _XXX____,________,
  _XXX___X,XX______,
  __XXXXXX,X_______,
  ___XXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00EB[ 40] = { /* code 00EB, LATIN SMALL LETTER E WITH DIAERESIS */
  ________,________,
  ________,________,
  ________,________,
  ___XX__X,X_______,
  ___XX__X,X_______,
  ________,________,
  ___XXXXX,________,
  __XXXXXX,X_______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  _XXX____,________,
  _XXX___X,XX______,
  __XXXXXX,X_______,
  ___XXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00EC[ 20] = { /* code 00EC, LATIN SMALL LETTER I WITH GRAVE */
  ________,
  ________,
  XXX_____,
  _XX_____,
  __XX____,
  ________,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00ED[ 20] = { /* code 00ED, LATIN SMALL LETTER I WITH ACUTE */
  ________,
  ________,
  __XXX___,
  __XX____,
  _XX_____,
  ________,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00EE[ 20] = { /* code 00EE, LATIN SMALL LETTER I WITH CIRCUMFLEX */
  ________,
  ________,
  ________,
  _XXX____,
  XX_XX___,
  ________,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00EF[ 20] = { /* code 00EF, LATIN SMALL LETTER I WITH DIAERESIS */
  ________,
  ________,
  ________,
  XX_XX___,
  XX_XX___,
  ________,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00F0[ 40] = { /* code 00F0, LATIN SMALL LETTER ETH */
  ________,________,
  ________,________,
  ________,________,
  ____XXX_,X_______,
  _____XXX,________,
  ____X__X,X_______,
  ____XXXX,X_______,
  __XXXXXX,XX______,
  __XXX_XX,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  __XXX_XX,X_______,
  __XXXXXX,X_______,
  ___XXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00F1[ 40] = { /* code 00F1, LATIN SMALL LETTER N WITH TILDE */
  ________,________,
  ________,________,
  ________,________,
  ___XXX__,X_______,
  ___X__XX,X_______,
  ________,________,
  _XXX_XXX,X_______,
  _XXXXXXX,XX______,
  _XXXX__X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00F2[ 40] = { /* code 00F2, LATIN SMALL LETTER O WITH GRAVE */
  ________,________,
  ________,________,
  ____XXX_,________,
  _____XX_,________,
  ______XX,________,
  ________,________,
  ___XXXXX,________,
  __XXXXXX,X_______,
  _XXXX_XX,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXXX_XX,XX______,
  __XXXXXX,X_______,
  ___XXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00F3[ 40] = { /* code 00F3, LATIN SMALL LETTER O WITH ACUTE */
  ________,________,
  ________,________,
  _____XXX,________,
  _____XX_,________,
  ____XX__,________,
  ________,________,
  ___XXXXX,________,
  __XXXXXX,X_______,
  _XXXX_XX,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXXX_XX,XX______,
  __XXXXXX,X_______,
  ___XXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00F4[ 40] = { /* code 00F4, LATIN SMALL LETTER O WITH CIRCUMFLEX */
  ________,________,
  ________,________,
  ________,________,
  ____XXX_,________,
  ___XX_XX,________,
  ________,________,
  ___XXXXX,________,
  __XXXXXX,X_______,
  _XXXX_XX,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXXX_XX,XX______,
  __XXXXXX,X_______,
  ___XXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00F5[ 40] = { /* code 00F5, LATIN SMALL LETTER O WITH TILDE */
  ________,________,
  ________,________,
  ________,________,
  ___XXX__,X_______,
  ___X__XX,X_______,
  ________,________,
  ___XXXXX,________,
  __XXXXXX,X_______,
  _XXXX_XX,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXXX_XX,XX______,
  __XXXXXX,X_______,
  ___XXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00F6[ 40] = { /* code 00F6, LATIN SMALL LETTER O WITH DIAERESIS */
  ________,________,
  ________,________,
  ________,________,
  ___XX__X,X_______,
  ___XX__X,X_______,
  ________,________,
  ___XXXXX,________,
  __XXXXXX,X_______,
  _XXXX_XX,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXXX_XX,XX______,
  __XXXXXX,X_______,
  ___XXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00F7[ 40] = { /* code 00F7, DIVISION SIGN */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ________,________,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  ________,________,
  ___XXX__,________,
  ___XXX__,________,
  ___XXX__,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00F8[ 40] = { /* code 00F8, LATIN SMALL LETTER O WITH STROKE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,X_______,
  ___XXXX_,XX______,
  __XXXXXX,X_______,
  __XXX_XX,X_______,
  _XXX__XX,XX______,
  _XXX_XXX,XX______,
  _XXXXX_X,XX______,
  _XXXX__X,XX______,
  __XXX_XX,X_______,
  __XXXXXX,X_______,
  _XX_XXXX,________,
  __X_____,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00F9[ 40] = { /* code 00F9, LATIN SMALL LETTER U WITH GRAVE */
  ________,________,
  ________,________,
  ___XXX__,________,
  ____XX__,________,
  _____XX_,________,
  ________,________,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX__XX,XX______,
  _XXXXXXX,XX______,
  __XXXX_X,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00FA[ 40] = { /* code 00FA, LATIN SMALL LETTER U WITH ACUTE */
  ________,________,
  ________,________,
  _____XXX,________,
  _____XX_,________,
  ____XX__,________,
  ________,________,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX__XX,XX______,
  _XXXXXXX,XX______,
  __XXXX_X,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00FB[ 40] = { /* code 00FB, LATIN SMALL LETTER U WITH CIRCUMFLEX */
  ________,________,
  ________,________,
  ________,________,
  ____XXX_,________,
  ___XX_XX,________,
  ________,________,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX__XX,XX______,
  _XXXXXXX,XX______,
  __XXXX_X,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00FC[ 40] = { /* code 00FC, LATIN SMALL LETTER U WITH DIAERESIS */
  ________,________,
  ________,________,
  ________,________,
  ___XX__X,X_______,
  ___XX__X,X_______,
  ________,________,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX__XX,XX______,
  _XXXXXXX,XX______,
  __XXXX_X,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00FD[ 40] = { /* code 00FD, LATIN SMALL LETTER Y WITH ACUTE */
  ________,________,
  ________,________,
  _____XXX,________,
  _____XX_,________,
  ____XX__,________,
  ________,________,
  XXX_____,XX______,
  XXX_____,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  __XX___X,X_______,
  __XXX_XX,X_______,
  ___XX_XX,X_______,
  ___XXXXX,________,
  ___XXXXX,________,
  ____XXX_,________,
  ____XXX_,________,
  ___XXX__,________,
  _XXXXX__,________,
  _XXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00FE[ 40] = { /* code 00FE, LATIN SMALL LETTER THORN */
  ________,________,
  ________,________,
  ________,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX_XXX,________,
  _XXXXXXX,X_______,
  _XXXX_XX,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXXX_XX,XX______,
  _XXXXXXX,X_______,
  _XXX_XXX,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_1_00FF[ 40] = { /* code 00FF, LATIN SMALL LETTER Y WITH DIAERESIS */
  ________,________,
  ________,________,
  ________,________,
  ___XX__X,X_______,
  ___XX__X,X_______,
  ________,________,
  XXX_____,XX______,
  XXX_____,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  __XX___X,X_______,
  __XXX_XX,X_______,
  ___XX_XX,X_______,
  ___XXXXX,________,
  ___XXXXX,________,
  ____XXX_,________,
  ____XXX_,________,
  ___XXX__,________,
  _XXXXX__,________,
  _XXXX___,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Font20B_1_CharInfo[96] = {
   {   5,   5,  1, acGUI_Font20B_1_00A0 } /* code 00A0 */
  ,{   5,   5,  1, acGUI_Font20B_1_00A1 } /* code 00A1 */
  ,{  10,  10,  2, acGUI_Font20B_1_00A2 } /* code 00A2 */
  ,{  10,  10,  2, acGUI_Font20B_1_00A3 } /* code 00A3 */
  ,{  10,  10,  2, acGUI_Font20B_1_00A4 } /* code 00A4 */
  ,{  10,  10,  2, acGUI_Font20B_1_00A5 } /* code 00A5 */
  ,{   4,   4,  1, acGUI_Font20B_1_00A6 } /* code 00A6 */
  ,{  10,  10,  2, acGUI_Font20B_1_00A7 } /* code 00A7 */
  ,{   6,   6,  1, acGUI_Font20B_1_00A8 } /* code 00A8 */
  ,{  13,  13,  2, acGUI_Font20B_1_00A9 } /* code 00A9 */
  ,{   7,   7,  1, acGUI_Font20B_1_00AA } /* code 00AA */
  ,{  10,  10,  2, acGUI_Font20B_1_00AB } /* code 00AB */
  ,{  11,  11,  2, acGUI_Font20B_1_00AC } /* code 00AC */
  ,{   6,   6,  1, acGUI_Font20B_1_00AD } /* code 00AD */
  ,{  13,  13,  2, acGUI_Font20B_1_00AE } /* code 00AE */
  ,{  10,  10,  2, acGUI_Font20B_1_00AF } /* code 00AF */
  ,{   7,   7,  1, acGUI_Font20B_1_00B0 } /* code 00B0 */
  ,{  10,  10,  2, acGUI_Font20B_1_00B1 } /* code 00B1 */
  ,{   6,   6,  1, acGUI_Font20B_1_00B2 } /* code 00B2 */
  ,{   6,   6,  1, acGUI_Font20B_1_00B3 } /* code 00B3 */
  ,{   6,   6,  1, acGUI_Font20B_1_00B4 } /* code 00B4 */
  ,{  10,  10,  2, acGUI_Font20B_1_00B5 } /* code 00B5 */
  ,{  10,  10,  2, acGUI_Font20B_1_00B6 } /* code 00B6 */
  ,{   5,   5,  1, acGUI_Font20B_1_00B7 } /* code 00B7 */
  ,{   6,   6,  1, acGUI_Font20B_1_00B8 } /* code 00B8 */
  ,{   6,   6,  1, acGUI_Font20B_1_00B9 } /* code 00B9 */
  ,{   7,   7,  1, acGUI_Font20B_1_00BA } /* code 00BA */
  ,{  10,  10,  2, acGUI_Font20B_1_00BB } /* code 00BB */
  ,{  15,  15,  2, acGUI_Font20B_1_00BC } /* code 00BC */
  ,{  15,  15,  2, acGUI_Font20B_1_00BD } /* code 00BD */
  ,{  15,  15,  2, acGUI_Font20B_1_00BE } /* code 00BE */
  ,{  11,  11,  2, acGUI_Font20B_1_00BF } /* code 00BF */
  ,{  13,  13,  2, acGUI_Font20B_1_00C0 } /* code 00C0 */
  ,{  13,  13,  2, acGUI_Font20B_1_00C1 } /* code 00C1 */
  ,{  13,  13,  2, acGUI_Font20B_1_00C2 } /* code 00C2 */
  ,{  13,  13,  2, acGUI_Font20B_1_00C3 } /* code 00C3 */
  ,{  13,  13,  2, acGUI_Font20B_1_00C4 } /* code 00C4 */
  ,{  13,  13,  2, acGUI_Font20B_1_00C5 } /* code 00C5 */
  ,{  18,  18,  3, acGUI_Font20B_1_00C6 } /* code 00C6 */
  ,{  13,  13,  2, acGUI_Font20B_1_00C7 } /* code 00C7 */
  ,{  12,  12,  2, acGUI_Font20B_1_00C8 } /* code 00C8 */
  ,{  12,  12,  2, acGUI_Font20B_1_00C9 } /* code 00C9 */
  ,{  12,  12,  2, acGUI_Font20B_1_00CA } /* code 00CA */
  ,{  12,  12,  2, acGUI_Font20B_1_00CB } /* code 00CB */
  ,{   5,   5,  1, acGUI_Font20B_1_00CC } /* code 00CC */
  ,{   5,   5,  1, acGUI_Font20B_1_00CD } /* code 00CD */
  ,{   5,   5,  1, acGUI_Font20B_1_00CE } /* code 00CE */
  ,{   5,   5,  1, acGUI_Font20B_1_00CF } /* code 00CF */
  ,{  13,  13,  2, acGUI_Font20B_1_00D0 } /* code 00D0 */
  ,{  13,  13,  2, acGUI_Font20B_1_00D1 } /* code 00D1 */
  ,{  14,  14,  2, acGUI_Font20B_1_00D2 } /* code 00D2 */
  ,{  14,  14,  2, acGUI_Font20B_1_00D3 } /* code 00D3 */
  ,{  14,  14,  2, acGUI_Font20B_1_00D4 } /* code 00D4 */
  ,{  14,  14,  2, acGUI_Font20B_1_00D5 } /* code 00D5 */
  ,{  14,  14,  2, acGUI_Font20B_1_00D6 } /* code 00D6 */
  ,{  11,  11,  2, acGUI_Font20B_1_00D7 } /* code 00D7 */
  ,{  14,  14,  2, acGUI_Font20B_1_00D8 } /* code 00D8 */
  ,{  13,  13,  2, acGUI_Font20B_1_00D9 } /* code 00D9 */
  ,{  13,  13,  2, acGUI_Font20B_1_00DA } /* code 00DA */
  ,{  13,  13,  2, acGUI_Font20B_1_00DB } /* code 00DB */
  ,{  13,  13,  2, acGUI_Font20B_1_00DC } /* code 00DC */
  ,{  12,  12,  2, acGUI_Font20B_1_00DD } /* code 00DD */
  ,{  12,  12,  2, acGUI_Font20B_1_00DE } /* code 00DE */
  ,{  12,  12,  2, acGUI_Font20B_1_00DF } /* code 00DF */
  ,{  10,  10,  2, acGUI_Font20B_1_00E0 } /* code 00E0 */
  ,{  10,  10,  2, acGUI_Font20B_1_00E1 } /* code 00E1 */
  ,{  10,  10,  2, acGUI_Font20B_1_00E2 } /* code 00E2 */
  ,{  10,  10,  2, acGUI_Font20B_1_00E3 } /* code 00E3 */
  ,{  10,  10,  2, acGUI_Font20B_1_00E4 } /* code 00E4 */
  ,{  10,  10,  2, acGUI_Font20B_1_00E5 } /* code 00E5 */
  ,{  16,  16,  2, acGUI_Font20B_1_00E6 } /* code 00E6 */
  ,{  10,  10,  2, acGUI_Font20B_1_00E7 } /* code 00E7 */
  ,{  10,  10,  2, acGUI_Font20B_1_00E8 } /* code 00E8 */
  ,{  10,  10,  2, acGUI_Font20B_1_00E9 } /* code 00E9 */
  ,{  10,  10,  2, acGUI_Font20B_1_00EA } /* code 00EA */
  ,{  10,  10,  2, acGUI_Font20B_1_00EB } /* code 00EB */
  ,{   5,   5,  1, acGUI_Font20B_1_00EC } /* code 00EC */
  ,{   5,   5,  1, acGUI_Font20B_1_00ED } /* code 00ED */
  ,{   5,   5,  1, acGUI_Font20B_1_00EE } /* code 00EE */
  ,{   5,   5,  1, acGUI_Font20B_1_00EF } /* code 00EF */
  ,{  11,  11,  2, acGUI_Font20B_1_00F0 } /* code 00F0 */
  ,{  11,  11,  2, acGUI_Font20B_1_00F1 } /* code 00F1 */
  ,{  11,  11,  2, acGUI_Font20B_1_00F2 } /* code 00F2 */
  ,{  11,  11,  2, acGUI_Font20B_1_00F3 } /* code 00F3 */
  ,{  11,  11,  2, acGUI_Font20B_1_00F4 } /* code 00F4 */
  ,{  11,  11,  2, acGUI_Font20B_1_00F5 } /* code 00F5 */
  ,{  11,  11,  2, acGUI_Font20B_1_00F6 } /* code 00F6 */
  ,{  10,  10,  2, acGUI_Font20B_1_00F7 } /* code 00F7 */
  ,{  11,  11,  2, acGUI_Font20B_1_00F8 } /* code 00F8 */
  ,{  11,  11,  2, acGUI_Font20B_1_00F9 } /* code 00F9 */
  ,{  11,  11,  2, acGUI_Font20B_1_00FA } /* code 00FA */
  ,{  11,  11,  2, acGUI_Font20B_1_00FB } /* code 00FB */
  ,{  11,  11,  2, acGUI_Font20B_1_00FC } /* code 00FC */
  ,{  10,  10,  2, acGUI_Font20B_1_00FD } /* code 00FD */
  ,{  11,  11,  2, acGUI_Font20B_1_00FE } /* code 00FE */
  ,{  10,  10,  2, acGUI_Font20B_1_00FF } /* code 00FF */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font20B_1_Prop1 = {
   0x00A0                                 /* first character */
  ,0x00FF                                 /* last character  */
  ,&GUI_Font20B_1_CharInfo[  0]           /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0   /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font20B_1_Prop0 = {
   0x0020                                 /* first character */
  ,0x007E                                 /* last character  */
  ,&GUI_Font20B_ASCII_CharInfo[  0]       /* address of first character */
  ,&GUI_Font20B_1_Prop1                   /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Font20B_1 = {
   GUI_FONTTYPE_PROP                      /* type of font    */
  ,20                                     /* height of font  */
  ,20                                     /* space of font y */
  ,1                                      /* magnification x */
  ,1                                      /* magnification y */
  ,{&GUI_Font20B_1_Prop0}
  ,16                                     /* Baseline */
  ,10                                     /* Height of lowercase characters */
  ,13                                     /* Height of capital characters */
};                                        

/*************************** End of file ****************************/
