/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
**********************************************************************
*                                                                    *
*        (c) 1996 - 2010  SEGGER Microcontroller GmbH & Co. KG       *
*                                                                    *
*        Internet: www.segger.com    Support:  support@segger.com    *
*                                                                    *
**********************************************************************

** emWin V5.06 - Graphical user interface for embedded applications **
emWin is protected by international copyright laws.   Knowledge of the
source code may not be used to write a similar product.  This file may
only be used in accordance with a license and should not be re-
distributed in any way. We appreciate your understanding and fairness.
----------------------------------------------------------------------
File        : F20B_ASCII.C
Purpose     : ASCII Character Set, bold
Height      : 20
---------------------------END-OF-HEADER------------------------------
*/

#include "GUI_FontIntern.h"

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0020[ 20] = { /* code 0020, SPACE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0021[ 20] = { /* code 0021, EXCLAMATION MARK */
  ________,
  ________,
  ________,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  __X_____,
  __X_____,
  ________,
  _XXX____,
  _XXX____,
  _XXX____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0022[ 40] = { /* code 0022, QUOTATION MARK */
  ________,________,
  ________,________,
  ________,________,
  _XXX_XXX,________,
  _XXX_XXX,________,
  _XXX_XXX,________,
  _XXX_XXX,________,
  _XXX_XXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0023[ 40] = { /* code 0023, NUMBER SIGN */
  ________,________,
  ________,________,
  ________,________,
  ____XX__,XX______,
  ____XX__,XX______,
  ___XX__X,X_______,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  ___XX__X,X_______,
  __XXX_XX,X_______,
  __XX__XX,________,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  __XX__XX,________,
  _XX__XX_,________,
  _XX__XX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0024[ 40] = { /* code 0024, DOLLAR SIGN */
  ________,________,
  ________,________,
  ____X___,________,
  __XXXXX_,________,
  _XXXXXXX,________,
  XXX_X_XX,X_______,
  XXX_X___,________,
  XXX_X___,________,
  _XXXXX__,________,
  __XXXXXX,________,
  ____XXXX,X_______,
  ____X_XX,X_______,
  XXX_X_XX,X_______,
  XXX_X_XX,X_______,
  _XXXXXXX,________,
  __XXXXX_,________,
  ____X___,________,
  ____X___,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0025[ 60] = { /* code 0025, PERCENT SIGN */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  __XXXX__,___XX___,________,
  _XX__XX_,__XX____,________,
  _XX__XX_,__XX____,________,
  _XX__XX_,_XX_____,________,
  _XX__XX_,_XX_____,________,
  __XXXX__,XX______,________,
  ________,XX______,________,
  _______X,X_______,________,
  _______X,X__XXXX_,________,
  ______XX,__XX__XX,________,
  ______XX,__XX__XX,________,
  _____XX_,__XX__XX,________,
  _____XX_,__XX__XX,________,
  ____XX__,___XXXX_,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0026[ 40] = { /* code 0026, AMPERSAND */
  ________,________,
  ________,________,
  ________,________,
  ____XXXX,________,
  __XXXXXX,XX______,
  __XXX__X,XX______,
  __XXX__X,XX______,
  ___XXX_X,X_______,
  ____XXXX,________,
  ___XXXXX,________,
  __XXXXXX,X_XX____,
  _XXX__XX,XXXX____,
  _XXX___X,XXX_____,
  _XXX___X,XXXX____,
  __XXXXXX,XXXXX___,
  ___XXXXX,___X____,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0027[ 20] = { /* code 0027, APOSTROPHE */
  ________,
  ________,
  ________,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0028[ 20] = { /* code 0028, LEFT PARENTHESIS */
  ________,
  ________,
  ________,
  ___XX___,
  __XXX___,
  __XXX___,
  __XX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  __XX____,
  __XX____,
  __XXX___,
  ___XX___};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0029[ 20] = { /* code 0029, RIGHT PARENTHESIS */
  ________,
  ________,
  ________,
  _XX_____,
  _XXX____,
  _XXX____,
  __XX____,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XX____,
  _XXX____,
  _XXX____,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_002A[ 20] = { /* code 002A, ASTERISK */
  ________,
  ________,
  ________,
  __XX____,
  X_XX_X__,
  XXXXXX__,
  __XX____,
  _XXXX___,
  XX__XX__,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_002B[ 40] = { /* code 002B, PLUS SIGN */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_002C[ 20] = { /* code 002C, COMMA */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  _XXX____,
  _XXX____,
  ___X____,
  __XX____,
  _XX_____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_002D[ 20] = { /* code 002D, HYPHEN-MINUS */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_002E[ 20] = { /* code 002E, FULL STOP */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  _XXX____,
  _XXX____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_002F[ 20] = { /* code 002F, SOLIDUS */
  ________,
  ________,
  ________,
  ___XX___,
  ___XX___,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  _XXX____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  XX______,
  XX______,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0030[ 40] = { /* code 0030, DIGIT ZERO */
  ________,________,
  ________,________,
  ________,________,
  ___XXXX_,________,
  __XXXXXX,________,
  __XX__XX,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  __XX__XX,________,
  __XXXXXX,________,
  ___XXXX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0031[ 40] = { /* code 0031, DIGIT ONE */
  ________,________,
  ________,________,
  ________,________,
  _____XX_,________,
  ____XXX_,________,
  __XXXXX_,________,
  _XXXXXX_,________,
  _XX_XXX_,________,
  _X__XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0032[ 40] = { /* code 0032, DIGIT TWO */
  ________,________,
  ________,________,
  ________,________,
  ___XXXX_,________,
  __XXXXXX,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  ______XX,X_______,
  _____XXX,________,
  _____XXX,________,
  ____XXX_,________,
  ___XXX__,________,
  ___XXX__,________,
  __XXX___,________,
  _XXXXXXX,X_______,
  _XXXXXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0033[ 40] = { /* code 0033, DIGIT THREE */
  ________,________,
  ________,________,
  ________,________,
  ___XXXX_,________,
  __XXXXXX,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  ______XX,X_______,
  ____XXXX,________,
  ____XXXX,________,
  ______XX,X_______,
  ______XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  __XXXXXX,________,
  ___XXXX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0034[ 40] = { /* code 0034, DIGIT FOUR */
  ________,________,
  ________,________,
  ________,________,
  _____XXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ___XXXXX,________,
  __XX_XXX,________,
  __XX_XXX,________,
  _XX__XXX,________,
  XX___XXX,________,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0035[ 40] = { /* code 0035, DIGIT FIVE */
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,________,
  ___XXXXX,________,
  __XXX___,________,
  __XX____,________,
  __XXXXX_,________,
  __XXXXXX,________,
  _XXX__XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  _XXX__XX,X_______,
  __XXXXXX,________,
  ___XXXX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0036[ 40] = { /* code 0036, DIGIT SIX */
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,________,
  __XXXXXX,X_______,
  __XX__XX,X_______,
  _XXX____,________,
  _XXXXXX_,________,
  _XXXXXXX,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  __XX__XX,X_______,
  __XXXXXX,________,
  ___XXXX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0037[ 40] = { /* code 0037, DIGIT SEVEN */
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,X_______,
  _XXXXXXX,X_______,
  ______XX,X_______,
  _____XXX,________,
  _____XX_,________,
  ____XXX_,________,
  ____XX__,________,
  ___XXX__,________,
  ___XXX__,________,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  __XXX___,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0038[ 40] = { /* code 0038, DIGIT EIGHT */
  ________,________,
  ________,________,
  ________,________,
  ___XXXX_,________,
  __XXXXXX,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  __XXXXXX,________,
  ___XXXX_,________,
  __XX__XX,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  __XXXXXX,________,
  ___XXXX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0039[ 40] = { /* code 0039, DIGIT NINE */
  ________,________,
  ________,________,
  ________,________,
  ___XXXX_,________,
  __XXXXXX,________,
  _XXX__XX,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  __XXXXXX,X_______,
  ___XXXXX,X_______,
  ______XX,X_______,
  _XXX__XX,________,
  __XXXXXX,________,
  ___XXXX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_003A[ 20] = { /* code 003A, COLON */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  __XXX___,
  __XXX___,
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  __XXX___,
  __XXX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_003B[ 20] = { /* code 003B, SEMICOLON */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  __XXX___,
  __XXX___,
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  __XXX___,
  __XXX___,
  ____X___,
  ___XX___,
  __XX____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_003C[ 40] = { /* code 003C, LESS-THAN SIGN */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,_X______,
  _______X,XX______,
  ____XXXX,XX______,
  __XXXXXX,________,
  _XXXX___,________,
  _XXXX___,________,
  __XXXXXX,________,
  ____XXXX,XX______,
  _______X,XX______,
  ________,_X______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_003D[ 40] = { /* code 003D, EQUALS SIGN */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  ________,________,
  ________,________,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_003E[ 40] = { /* code 003E, GREATER-THAN SIGN */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _X______,________,
  _XXX____,________,
  _XXXXXX_,________,
  ___XXXXX,X_______,
  ______XX,XX______,
  ______XX,XX______,
  ___XXXXX,X_______,
  _XXXXXX_,________,
  _XXX____,________,
  _X______,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_003F[ 40] = { /* code 003F, QUESTION MARK */
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,________,
  __XXXXXX,X_______,
  _XXXX__X,XX______,
  _XXX___X,XX______,
  ______XX,XX______,
  _____XXX,X_______,
  ____XXXX,________,
  ____XXX_,________,
  ____XXX_,________,
  ________,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0040[ 60] = { /* code 0040, COMMERCIAL AT */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _______X,XXXXX___,________,
  _____XXX,XXXXXXX_,________,
  ___XXXX_,____XXXX,________,
  ___XX__X,XX_XX_XX,________,
  __XX__XX,XXXXX_XX,X_______,
  __XX_XX_,__XXX__X,X_______,
  _XX_XXX_,__XXX__X,X_______,
  _XX_XX__,__XX___X,X_______,
  _XX_XX__,__XX___X,X_______,
  _XX_XX__,_XXX__XX,________,
  _XX_XX__,_XXX_XXX,________,
  _XX__XXX,XXXXXXX_,________,
  __XX_XXX,X_XXX___,________,
  __XXX___,_______X,XX______,
  ___XXXX_,_____XXX,X_______,
  ____XXXX,XXXXXXXX,________,
  ______XX,XXXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0041[ 40] = { /* code 0041, LATIN CAPITAL LETTER A */
  ________,________,
  ________,________,
  ________,________,
  ____XXXX,X_______,
  ____XXXX,X_______,
  ____XXXX,X_______,
  ___XXX_X,XX______,
  ___XXX_X,XX______,
  ___XXX_X,XX______,
  __XXX___,XXX_____,
  __XXXXXX,XXX_____,
  __XXXXXX,XXX_____,
  _XXXXXXX,XXXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  XXX_____,__XXX___,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0042[ 40] = { /* code 0042, LATIN CAPITAL LETTER B */
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XX______,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XX______,
  _XXXXXXX,XXX_____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXXXXXX,XXXX____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0043[ 40] = { /* code 0043, LATIN CAPITAL LETTER C */
  ________,________,
  ________,________,
  ________,________,
  _____XXX,X_______,
  ___XXXXX,XXX_____,
  __XXXXXX,XXX_____,
  __XXX___,XXXX____,
  _XXX____,_XX_____,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,_XX_____,
  __XXX___,XXXX____,
  __XXXXXX,XXX_____,
  ___XXXXX,XXX_____,
  _____XXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0044[ 40] = { /* code 0044, LATIN CAPITAL LETTER D */
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,X_______,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXX____,XXXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,XXXX____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0045[ 40] = { /* code 0045, LATIN CAPITAL LETTER E */
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXX____,________,
  _XXX____,________,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXX____,________,
  _XXX____,________,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0046[ 40] = { /* code 0046, LATIN CAPITAL LETTER F */
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  _XXX____,________,
  _XXX____,________,
  _XXXXXXX,X_______,
  _XXXXXXX,X_______,
  _XXXXXXX,X_______,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0047[ 40] = { /* code 0047, LATIN CAPITAL LETTER G */
  ________,________,
  ________,________,
  ________,________,
  _____XXX,XX______,
  ___XXXXX,XXXX____,
  __XXXXXX,XXXX____,
  __XXX___,_XXXX___,
  _XXX____,__XX____,
  _XXX____,________,
  _XXX___X,XXXXX___,
  _XXX___X,XXXXX___,
  _XXX___X,XXXXX___,
  __XXX___,__XXX___,
  __XXXXXX,XXXXX___,
  ___XXXXX,XXXX____,
  _____XXX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0048[ 40] = { /* code 0048, LATIN CAPITAL LETTER H */
  ________,________,
  ________,________,
  ________,________,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXXXXXX,XXXX____,
  _XXXXXXX,XXXX____,
  _XXXXXXX,XXXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0049[ 20] = { /* code 0049, LATIN CAPITAL LETTER I */
  ________,
  ________,
  ________,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_004A[ 40] = { /* code 004A, LATIN CAPITAL LETTER J */
  ________,________,
  ________,________,
  ________,________,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  ______XX,X_______,
  XXX___XX,X_______,
  XXX___XX,X_______,
  XXXXXXXX,X_______,
  _XXXXXXX,________,
  __XXXXX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_004B[ 40] = { /* code 004B, LATIN CAPITAL LETTER K */
  ________,________,
  ________,________,
  ________,________,
  _XXX____,XXXX____,
  _XXX___X,XXX_____,
  _XXX___X,XX______,
  _XXX__XX,X_______,
  _XXX_XXX,________,
  _XXXXXXX,________,
  _XXXXXXX,X_______,
  _XXXX_XX,X_______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX____,XXX_____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_004C[ 40] = { /* code 004C, LATIN CAPITAL LETTER L */
  ________,________,
  ________,________,
  ________,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_004D[ 40] = { /* code 004D, LATIN CAPITAL LETTER M */
  ________,________,
  ________,________,
  ________,________,
  _XXXX___,__XXXX__,
  _XXXX___,__XXXX__,
  _XXXXX__,_XXXXX__,
  _XXXXX__,_XXXXX__,
  _XXXXX__,_XXXXX__,
  _XXX_XX_,XX_XXX__,
  _XXX_XX_,XX_XXX__,
  _XXX_XX_,XX_XXX__,
  _XXX_XX_,XX_XXX__,
  _XXX__XX,X__XXX__,
  _XXX__XX,X__XXX__,
  _XXX__XX,X__XXX__,
  _XXX___X,___XXX__,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_004E[ 40] = { /* code 004E, LATIN CAPITAL LETTER N */
  ________,________,
  ________,________,
  ________,________,
  _XXX____,_XXX____,
  _XXXX___,_XXX____,
  _XXXXX__,_XXX____,
  _XXXXX__,_XXX____,
  _XXXXXX_,_XXX____,
  _XXX_XX_,_XXX____,
  _XXX_XXX,_XXX____,
  _XXX__XX,_XXX____,
  _XXX__XX,XXXX____,
  _XXX___X,XXXX____,
  _XXX___X,XXXX____,
  _XXX____,XXXX____,
  _XXX____,_XXX____,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_004F[ 40] = { /* code 004F, LATIN CAPITAL LETTER O */
  ________,________,
  ________,________,
  ________,________,
  _____XXX,X_______,
  ___XXXXX,XXX_____,
  __XXXXXX,XXXX____,
  __XXX___,_XXX____,
  _XXX____,__XXX___,
  _XXX____,__XXX___,
  _XXX____,__XXX___,
  _XXX____,__XXX___,
  _XXX____,__XXX___,
  __XXX___,_XXX____,
  __XXXXXX,XXXX____,
  ___XXXXX,XXX_____,
  _____XXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0050[ 40] = { /* code 0050, LATIN CAPITAL LETTER P */
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,X_______,
  _XXXXXXX,XX______,
  _XXXXXXX,XXX_____,
  _XXX____,XXX_____,
  _XXX____,XXX_____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XX______,
  _XXXXXXX,X_______,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0051[ 40] = { /* code 0051, LATIN CAPITAL LETTER Q */
  ________,________,
  ________,________,
  ________,________,
  ____XXXX,XX______,
  ___XXXXX,XXX_____,
  __XXXXXX,XXXX____,
  __XXX___,_XXX____,
  _XXX____,__XXX___,
  _XXX____,__XXX___,
  _XXX____,__XXX___,
  _XXX___X,__XXX___,
  _XXX__XX,XXXXX___,
  __XXX__X,XXXXX___,
  __XXXXXX,XXXX____,
  ___XXXXX,XXXX____,
  ____XXXX,X_XXX___,
  ________,___X____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0052[ 40] = { /* code 0052, LATIN CAPITAL LETTER R */
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XX______,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXXXXXX,XXXX____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,X_______,
  _XXX__XX,XX______,
  _XXX___X,XXX_____,
  _XXX____,XXX_____,
  _XXX____,XXXX____,
  _XXX____,_XXXX___,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0053[ 40] = { /* code 0053, LATIN CAPITAL LETTER S */
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,X_______,
  __XXXXXX,XX______,
  _XXXXXXX,XXX_____,
  _XXX____,XXX_____,
  _XXX____,________,
  _XXXXXXX,________,
  __XXXXXX,XX______,
  ____XXXX,XXX_____,
  ________,XXX_____,
  _XXX____,XXX_____,
  _XXXXXXX,XXX_____,
  __XXXXXX,XX______,
  ___XXXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0054[ 40] = { /* code 0054, LATIN CAPITAL LETTER T */
  ________,________,
  ________,________,
  ________,________,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0055[ 40] = { /* code 0055, LATIN CAPITAL LETTER U */
  ________,________,
  ________,________,
  ________,________,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXXX___,XXXX____,
  __XXXXXX,XXX_____,
  __XXXXXX,XXX_____,
  ____XXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0056[ 40] = { /* code 0056, LATIN CAPITAL LETTER V */
  ________,________,
  ________,________,
  ________,________,
  XXX_____,__XXX___,
  XXX_____,__XXX___,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  __XXX___,XXX_____,
  __XXX___,XXX_____,
  ___XXX_X,XX______,
  ___XXX_X,XX______,
  ___XXX_X,XX______,
  ____XXXX,X_______,
  ____XXXX,X_______,
  ____XXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0057[ 60] = { /* code 0057, LATIN CAPITAL LETTER W */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  XXX____X,XX____XX,X_______,
  XXX____X,XX____XX,X_______,
  XXX___XX,XXX___XX,X_______,
  _XXX__XX,_XX__XXX,________,
  _XXX__XX,_XX__XXX,________,
  _XXX_XXX,_XXX_XXX,________,
  _XXX_XXX,_XXX_XXX,________,
  _XXX_XX_,__XX_XXX,________,
  _XXX_XX_,__XX_XXX,________,
  __XXXXX_,__XXXXX_,________,
  __XXXXX_,__XXXXX_,________,
  __XXXX__,___XXXX_,________,
  __XXXX__,___XXXX_,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0058[ 40] = { /* code 0058, LATIN CAPITAL LETTER X */
  ________,________,
  ________,________,
  ________,________,
  _XXX____,XXX_____,
  _XXX____,XXX_____,
  __XXX__X,XX______,
  ___XX__X,X_______,
  ___XXXXX,X_______,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ___XXXXX,X_______,
  ___XX__X,X_______,
  __XXX__X,XX______,
  _XXX____,XXX_____,
  _XXX____,XXX_____,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0059[ 40] = { /* code 0059, LATIN CAPITAL LETTER Y */
  ________,________,
  ________,________,
  ________,________,
  _XXX____,_XXX____,
  _XXX____,_XXX____,
  __XXX___,XXX_____,
  ___XXX_X,XX______,
  ___XXX_X,XX______,
  ____XXXX,X_______,
  ____XXXX,X_______,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  _____XXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_005A[ 40] = { /* code 005A, LATIN CAPITAL LETTER Z */
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  ______XX,X_______,
  _____XXX,________,
  ____XXX_,________,
  ___XXXX_,________,
  ___XXX__,________,
  __XXX___,________,
  _XXX____,________,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_005B[ 20] = { /* code 005B, LEFT SQUARE BRACKET */
  ________,
  ________,
  ________,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXXXX__,
  _XXXXX__,
  _XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_005C[ 20] = { /* code 005C, REVERSE SOLIDUS */
  ________,
  ________,
  ________,
  XX______,
  XX______,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XXX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  ___XX___,
  ___XX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_005D[ 20] = { /* code 005D, RIGHT SQUARE BRACKET */
  ________,
  ________,
  ________,
  XXXXX___,
  XXXXX___,
  XXXXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  XXXXX___,
  XXXXX___,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_005E[ 40] = { /* code 005E, CIRCUMFLEX ACCENT */
  ________,________,
  ________,________,
  ________,________,
  ____XXX_,________,
  ____XXX_,________,
  ___XXXXX,________,
  ___XX_XX,________,
  __XXX_XX,X_______,
  __XX___X,X_______,
  _XXX___X,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_005F[ 40] = { /* code 005F, LOW LINE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0060[ 20] = { /* code 0060, GRAVE ACCENT */
  ________,
  ________,
  ________,
  XXX_____,
  _XX_____,
  __XX____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0061[ 40] = { /* code 0061, LATIN SMALL LETTER A */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,________,
  __XXXXXX,X_______,
  _XX___XX,X_______,
  _____XXX,X_______,
  ___XXXXX,X_______,
  __XXX_XX,X_______,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXXXXXX,X_______,
  __XXXX_X,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0062[ 40] = { /* code 0062, LATIN SMALL LETTER B */
  ________,________,
  ________,________,
  ________,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX_XXX,________,
  _XXXXXXX,X_______,
  _XXXX_XX,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXXX_XX,XX______,
  _XXXXXXX,X_______,
  _XXX_XXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0063[ 40] = { /* code 0063, LATIN SMALL LETTER C */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXX_,________,
  __XXXXXX,________,
  _XXXX_XX,X_______,
  _XXX___X,________,
  _XXX____,________,
  _XXX____,________,
  _XXX___X,________,
  _XXXX_XX,X_______,
  __XXXXXX,________,
  ___XXXX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0064[ 40] = { /* code 0064, LATIN SMALL LETTER D */
  ________,________,
  ________,________,
  ________,________,
  _______X,XX______,
  _______X,XX______,
  _______X,XX______,
  ___XXX_X,XX______,
  __XXXXXX,XX______,
  _XXXX_XX,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXXX_XX,XX______,
  __XXXXXX,XX______,
  ___XXX_X,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0065[ 40] = { /* code 0065, LATIN SMALL LETTER E */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,________,
  __XXXXXX,X_______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXXXXXX,XX______,
  _XXXXXXX,XX______,
  _XXX____,________,
  _XXX___X,XX______,
  __XXXXXX,X_______,
  ___XXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0066[ 20] = { /* code 0066, LATIN SMALL LETTER F */
  ________,
  ________,
  ________,
  __XXXX__,
  _XXXXX__,
  _XXX____,
  XXXXXX__,
  XXXXXX__,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0067[ 40] = { /* code 0067, LATIN SMALL LETTER G */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXX_X,XX______,
  __XXXXXX,XX______,
  _XXXX_XX,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXXX_XX,XX______,
  __XXXXXX,XX______,
  ___XXX_X,XX______,
  _______X,XX______,
  _XXX___X,XX______,
  _XXXXXXX,X_______,
  __XXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0068[ 40] = { /* code 0068, LATIN SMALL LETTER H */
  ________,________,
  ________,________,
  ________,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX_XXX,X_______,
  _XXXXXXX,XX______,
  _XXXX__X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0069[ 20] = { /* code 0069, LATIN SMALL LETTER I */
  ________,
  ________,
  ________,
  _XXX____,
  _XXX____,
  ________,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_006A[ 20] = { /* code 006A, LATIN SMALL LETTER J */
  ________,
  ________,
  ________,
  _XXX____,
  _XXX____,
  ________,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  XXXX____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_006B[ 40] = { /* code 006B, LATIN SMALL LETTER K */
  ________,________,
  ________,________,
  ________,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX___X,XX______,
  _XXX__XX,X_______,
  _XXX_XXX,________,
  _XXXXXX_,________,
  _XXXXXX_,________,
  _XXXXXXX,________,
  _XXX_XXX,________,
  _XXX__XX,X_______,
  _XXX__XX,X_______,
  _XXX___X,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_006C[ 20] = { /* code 006C, LATIN SMALL LETTER L */
  ________,
  ________,
  ________,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_006D[ 60] = { /* code 006D, LATIN SMALL LETTER M */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _XXX_XXX,X__XXXX_,________,
  _XXXXXXX,XXXXXXXX,________,
  _XXXX__X,XXX__XXX,________,
  _XXX___X,XX___XXX,________,
  _XXX___X,XX___XXX,________,
  _XXX___X,XX___XXX,________,
  _XXX___X,XX___XXX,________,
  _XXX___X,XX___XXX,________,
  _XXX___X,XX___XXX,________,
  _XXX___X,XX___XXX,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_006E[ 40] = { /* code 006E, LATIN SMALL LETTER N */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXX_XXX,X_______,
  _XXXXXXX,XX______,
  _XXXX__X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_006F[ 40] = { /* code 006F, LATIN SMALL LETTER O */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,________,
  __XXXXXX,X_______,
  _XXXX_XX,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXXX_XX,XX______,
  __XXXXXX,X_______,
  ___XXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0070[ 40] = { /* code 0070, LATIN SMALL LETTER P */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXX_XXX,________,
  _XXXXXXX,X_______,
  _XXXX_XX,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXXX_XX,XX______,
  _XXXXXXX,X_______,
  _XXX_XXX,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________,
  _XXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0071[ 40] = { /* code 0071, LATIN SMALL LETTER Q */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXX_X,XX______,
  __XXXXXX,XX______,
  _XXXX_XX,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXXX_XX,XX______,
  __XXXXXX,XX______,
  ___XXX_X,XX______,
  _______X,XX______,
  _______X,XX______,
  _______X,XX______,
  _______X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0072[ 20] = { /* code 0072, LATIN SMALL LETTER R */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX_XX_,
  _XXXXXX_,
  _XXXX___,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0073[ 40] = { /* code 0073, LATIN SMALL LETTER S */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XXXXXX,________,
  _XXXXXXX,X_______,
  _XXX__XX,X_______,
  _XXXX___,________,
  __XXXXX_,________,
  ___XXXXX,________,
  _____XXX,X_______,
  _XXX__XX,X_______,
  _XXXXXXX,X_______,
  __XXXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0074[ 20] = { /* code 0074, LATIN SMALL LETTER T */
  ________,
  ________,
  ________,
  __XX____,
  _XXX____,
  _XXX____,
  XXXXXX__,
  XXXXXX__,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXX____,
  _XXXXX__,
  __XXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0075[ 40] = { /* code 0075, LATIN SMALL LETTER U */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX__XX,XX______,
  _XXXXXXX,XX______,
  __XXXX_X,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0076[ 40] = { /* code 0076, LATIN SMALL LETTER V */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXX___X,XX______,
  _XXX___X,XX______,
  _XXX___X,XX______,
  __XXX_XX,X_______,
  __XXX_XX,X_______,
  ___XX_XX,________,
  ___XXXXX,________,
  ___XXXXX,________,
  ____XXX_,________,
  ____XXX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0077[ 40] = { /* code 0077, LATIN SMALL LETTER W */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXX___XX,X___XXX_,
  XXX___XX,X___XXX_,
  _XX___XX,X___XX__,
  _XXX_XXX,XX_XXX__,
  _XXX_XX_,XX_XXX__,
  __XX_XX_,XX_XX___,
  __XXXXX_,XXXXX___,
  __XXXX__,_XXXX___,
  ___XXX__,_XXX____,
  ___XXX__,_XXX____,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0078[ 40] = { /* code 0078, LATIN SMALL LETTER X */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXX___X,XX______,
  __XXX_XX,X_______,
  __XXX_XX,X_______,
  ___XXXXX,________,
  ____XXX_,________,
  ____XXX_,________,
  ___XXXXX,________,
  __XXX_XX,X_______,
  __XXX_XX,X_______,
  _XXX___X,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_0079[ 40] = { /* code 0079, LATIN SMALL LETTER Y */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXX_____,XXX_____,
  XXX_____,XXX_____,
  _XXX___X,XX______,
  _XXX___X,XX______,
  __XX___X,X_______,
  __XXX_XX,X_______,
  ___XX_XX,X_______,
  ___XXXXX,________,
  ___XXXXX,________,
  ____XXX_,________,
  ____XXX_,________,
  ___XXX__,________,
  _XXXXX__,________,
  _XXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_007A[ 40] = { /* code 007A, LATIN SMALL LETTER Z */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,________,
  _XXXXXXX,________,
  _____XXX,________,
  ____XXX_,________,
  ___XXX__,________,
  ___XXX__,________,
  __XXX___,________,
  _XXX____,________,
  _XXXXXXX,________,
  _XXXXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_007B[ 20] = { /* code 007B, LEFT CURLY BRACKET */
  ________,
  ________,
  ________,
  ____XXX_,
  ___XXXX_,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  __XXX___,
  _XXX____,
  _XXX____,
  __XXX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XX___,
  ___XXXX_,
  ____XXX_};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_007C[ 20] = { /* code 007C, VERTICAL LINE */
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_007D[ 20] = { /* code 007D, RIGHT CURLY BRACKET */
  ________,
  ________,
  ________,
  XXX_____,
  XXXX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  __XXX___,
  ___XXX__,
  ___XXX__,
  __XXX___,
  __XX____,
  __XX____,
  __XX____,
  __XX____,
  XXXX____,
  XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Font20B_ASCII_007E[ 40] = { /* code 007E, TILDE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXX___,_X______,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  X____XXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Font20B_ASCII_CharInfo[95] = {
   {   5,   5,  1, acGUI_Font20B_ASCII_0020 } /* code 0020 */
  ,{   5,   5,  1, acGUI_Font20B_ASCII_0021 } /* code 0021 */
  ,{   9,   9,  2, acGUI_Font20B_ASCII_0022 } /* code 0022 */
  ,{  10,  10,  2, acGUI_Font20B_ASCII_0023 } /* code 0023 */
  ,{  10,  10,  2, acGUI_Font20B_ASCII_0024 } /* code 0024 */
  ,{  17,  17,  3, acGUI_Font20B_ASCII_0025 } /* code 0025 */
  ,{  13,  13,  2, acGUI_Font20B_ASCII_0026 } /* code 0026 */
  ,{   4,   4,  1, acGUI_Font20B_ASCII_0027 } /* code 0027 */
  ,{   6,   6,  1, acGUI_Font20B_ASCII_0028 } /* code 0028 */
  ,{   6,   6,  1, acGUI_Font20B_ASCII_0029 } /* code 0029 */
  ,{   7,   7,  1, acGUI_Font20B_ASCII_002A } /* code 002A */
  ,{  11,  11,  2, acGUI_Font20B_ASCII_002B } /* code 002B */
  ,{   5,   5,  1, acGUI_Font20B_ASCII_002C } /* code 002C */
  ,{   6,   6,  1, acGUI_Font20B_ASCII_002D } /* code 002D */
  ,{   5,   5,  1, acGUI_Font20B_ASCII_002E } /* code 002E */
  ,{   5,   5,  1, acGUI_Font20B_ASCII_002F } /* code 002F */
  ,{  10,  10,  2, acGUI_Font20B_ASCII_0030 } /* code 0030 */
  ,{  10,  10,  2, acGUI_Font20B_ASCII_0031 } /* code 0031 */
  ,{  10,  10,  2, acGUI_Font20B_ASCII_0032 } /* code 0032 */
  ,{  10,  10,  2, acGUI_Font20B_ASCII_0033 } /* code 0033 */
  ,{  10,  10,  2, acGUI_Font20B_ASCII_0034 } /* code 0034 */
  ,{  10,  10,  2, acGUI_Font20B_ASCII_0035 } /* code 0035 */
  ,{  10,  10,  2, acGUI_Font20B_ASCII_0036 } /* code 0036 */
  ,{  10,  10,  2, acGUI_Font20B_ASCII_0037 } /* code 0037 */
  ,{  10,  10,  2, acGUI_Font20B_ASCII_0038 } /* code 0038 */
  ,{  10,  10,  2, acGUI_Font20B_ASCII_0039 } /* code 0039 */
  ,{   7,   7,  1, acGUI_Font20B_ASCII_003A } /* code 003A */
  ,{   7,   7,  1, acGUI_Font20B_ASCII_003B } /* code 003B */
  ,{  11,  11,  2, acGUI_Font20B_ASCII_003C } /* code 003C */
  ,{  11,  11,  2, acGUI_Font20B_ASCII_003D } /* code 003D */
  ,{  11,  11,  2, acGUI_Font20B_ASCII_003E } /* code 003E */
  ,{  11,  11,  2, acGUI_Font20B_ASCII_003F } /* code 003F */
  ,{  18,  18,  3, acGUI_Font20B_ASCII_0040 } /* code 0040 */
  ,{  13,  13,  2, acGUI_Font20B_ASCII_0041 } /* code 0041 */
  ,{  13,  13,  2, acGUI_Font20B_ASCII_0042 } /* code 0042 */
  ,{  13,  13,  2, acGUI_Font20B_ASCII_0043 } /* code 0043 */
  ,{  13,  13,  2, acGUI_Font20B_ASCII_0044 } /* code 0044 */
  ,{  12,  12,  2, acGUI_Font20B_ASCII_0045 } /* code 0045 */
  ,{  11,  11,  2, acGUI_Font20B_ASCII_0046 } /* code 0046 */
  ,{  14,  14,  2, acGUI_Font20B_ASCII_0047 } /* code 0047 */
  ,{  13,  13,  2, acGUI_Font20B_ASCII_0048 } /* code 0048 */
  ,{   5,   5,  1, acGUI_Font20B_ASCII_0049 } /* code 0049 */
  ,{  10,  10,  2, acGUI_Font20B_ASCII_004A } /* code 004A */
  ,{  13,  13,  2, acGUI_Font20B_ASCII_004B } /* code 004B */
  ,{  11,  11,  2, acGUI_Font20B_ASCII_004C } /* code 004C */
  ,{  15,  15,  2, acGUI_Font20B_ASCII_004D } /* code 004D */
  ,{  13,  13,  2, acGUI_Font20B_ASCII_004E } /* code 004E */
  ,{  14,  14,  2, acGUI_Font20B_ASCII_004F } /* code 004F */
  ,{  12,  12,  2, acGUI_Font20B_ASCII_0050 } /* code 0050 */
  ,{  14,  14,  2, acGUI_Font20B_ASCII_0051 } /* code 0051 */
  ,{  13,  13,  2, acGUI_Font20B_ASCII_0052 } /* code 0052 */
  ,{  12,  12,  2, acGUI_Font20B_ASCII_0053 } /* code 0053 */
  ,{  11,  11,  2, acGUI_Font20B_ASCII_0054 } /* code 0054 */
  ,{  13,  13,  2, acGUI_Font20B_ASCII_0055 } /* code 0055 */
  ,{  13,  13,  2, acGUI_Font20B_ASCII_0056 } /* code 0056 */
  ,{  17,  17,  3, acGUI_Font20B_ASCII_0057 } /* code 0057 */
  ,{  12,  12,  2, acGUI_Font20B_ASCII_0058 } /* code 0058 */
  ,{  13,  13,  2, acGUI_Font20B_ASCII_0059 } /* code 0059 */
  ,{  10,  10,  2, acGUI_Font20B_ASCII_005A } /* code 005A */
  ,{   6,   6,  1, acGUI_Font20B_ASCII_005B } /* code 005B */
  ,{   5,   5,  1, acGUI_Font20B_ASCII_005C } /* code 005C */
  ,{   6,   6,  1, acGUI_Font20B_ASCII_005D } /* code 005D */
  ,{  11,  11,  2, acGUI_Font20B_ASCII_005E } /* code 005E */
  ,{  10,  10,  2, acGUI_Font20B_ASCII_005F } /* code 005F */
  ,{   6,   6,  1, acGUI_Font20B_ASCII_0060 } /* code 0060 */
  ,{  10,  10,  2, acGUI_Font20B_ASCII_0061 } /* code 0061 */
  ,{  11,  11,  2, acGUI_Font20B_ASCII_0062 } /* code 0062 */
  ,{  10,  10,  2, acGUI_Font20B_ASCII_0063 } /* code 0063 */
  ,{  11,  11,  2, acGUI_Font20B_ASCII_0064 } /* code 0064 */
  ,{  11,  11,  2, acGUI_Font20B_ASCII_0065 } /* code 0065 */
  ,{   6,   6,  1, acGUI_Font20B_ASCII_0066 } /* code 0066 */
  ,{  11,  11,  2, acGUI_Font20B_ASCII_0067 } /* code 0067 */
  ,{  11,  11,  2, acGUI_Font20B_ASCII_0068 } /* code 0068 */
  ,{   5,   5,  1, acGUI_Font20B_ASCII_0069 } /* code 0069 */
  ,{   5,   5,  1, acGUI_Font20B_ASCII_006A } /* code 006A */
  ,{  10,  10,  2, acGUI_Font20B_ASCII_006B } /* code 006B */
  ,{   5,   5,  1, acGUI_Font20B_ASCII_006C } /* code 006C */
  ,{  17,  17,  3, acGUI_Font20B_ASCII_006D } /* code 006D */
  ,{  11,  11,  2, acGUI_Font20B_ASCII_006E } /* code 006E */
  ,{  11,  11,  2, acGUI_Font20B_ASCII_006F } /* code 006F */
  ,{  11,  11,  2, acGUI_Font20B_ASCII_0070 } /* code 0070 */
  ,{  11,  11,  2, acGUI_Font20B_ASCII_0071 } /* code 0071 */
  ,{   7,   7,  1, acGUI_Font20B_ASCII_0072 } /* code 0072 */
  ,{  10,  10,  2, acGUI_Font20B_ASCII_0073 } /* code 0073 */
  ,{   6,   6,  1, acGUI_Font20B_ASCII_0074 } /* code 0074 */
  ,{  11,  11,  2, acGUI_Font20B_ASCII_0075 } /* code 0075 */
  ,{  11,  11,  2, acGUI_Font20B_ASCII_0076 } /* code 0076 */
  ,{  15,  15,  2, acGUI_Font20B_ASCII_0077 } /* code 0077 */
  ,{  11,  11,  2, acGUI_Font20B_ASCII_0078 } /* code 0078 */
  ,{  11,  11,  2, acGUI_Font20B_ASCII_0079 } /* code 0079 */
  ,{   9,   9,  2, acGUI_Font20B_ASCII_007A } /* code 007A */
  ,{   7,   7,  1, acGUI_Font20B_ASCII_007B } /* code 007B */
  ,{   4,   4,  1, acGUI_Font20B_ASCII_007C } /* code 007C */
  ,{   7,   7,  1, acGUI_Font20B_ASCII_007D } /* code 007D */
  ,{  11,  11,  2, acGUI_Font20B_ASCII_007E } /* code 007E */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font20B_ASCII_Prop1 = {
   0x0020                                     /* first character */
  ,0x007E                                     /* last character  */
  ,&GUI_Font20B_ASCII_CharInfo[  0]           /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0       /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Font20B_ASCII = {
   GUI_FONTTYPE_PROP                          /* type of font    */
  ,20                                         /* height of font  */
  ,20                                         /* space of font y */
  ,1                                          /* magnification x */
  ,1                                          /* magnification y */
  ,{&GUI_Font20B_ASCII_Prop1}
  ,16                                         /* Baseline */
  ,10                                         /* Height of lowercase characters */
  ,13                                         /* Height of capital characters */
};                                            

/*************************** End of file ****************************/
